# TCL File Generated by Component Editor 18.1
# Thu Aug 22 20:38:32 PDT 2019
# DO NOT MODIFY


# 
# spiral_fft_4096_unscaled_streaming_32bit "Spiral FFT 4096 Unscaled Streaming 32 Bit" v1.0
#  2019.08.22.20:38:32
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module spiral_fft_4096_unscaled_streaming_32bit
# 
set_module_property DESCRIPTION ""
set_module_property NAME spiral_fft_4096_unscaled_streaming_32bit
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Spiral FFT 4096 Unscaled Streaming 32 Bit"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dft_4096_fixed_32_bit_unscaled_stream_d
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dft_4096_fixed_32_bit_unscaled_stream_d.v VERILOG PATH dft_4096_fixed_32_bit_unscaled_stream_d.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end next next Input 1
add_interface_port conduit_end next_out next_out Output 1
add_interface_port conduit_end X0 x0 Input 32
add_interface_port conduit_end Y0 y0 Output 32
add_interface_port conduit_end X1 x1 Input 32
add_interface_port conduit_end Y1 y1 Output 32
add_interface_port conduit_end X2 x2 Input 32
add_interface_port conduit_end Y2 y2 Output 32
add_interface_port conduit_end X3 x3 Input 32
add_interface_port conduit_end Y3 y3 Output 32
add_interface_port conduit_end X4 x4 Input 32
add_interface_port conduit_end Y4 y4 Output 32
add_interface_port conduit_end X5 x5 Input 32
add_interface_port conduit_end Y5 y5 Output 32
add_interface_port conduit_end X6 x6 Input 32
add_interface_port conduit_end Y6 y6 Output 32
add_interface_port conduit_end X7 x7 Input 32
add_interface_port conduit_end Y7 y7 Output 32

