# TCL File Generated by Component Editor 14.0
# Tue Nov 25 14:34:15 CST 2014
# DO NOT MODIFY


# 
# avs_to_packets_tb "AVMM to LVDS TB" v1.0
#  2014.11.25.14:34:15
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module avs_to_packets_tb
# 
set_module_property DESCRIPTION ""
set_module_property NAME avs_to_packets_tb
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "AVMM to LVDS TB"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avmm_to_packets_tb
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avmm_sim_package.h OTHER PATH avmm_sim_package.h
add_fileset_file avs_to_packets_tb.sv SYSTEM_VERILOG PATH avs_to_packets_tb.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avmm_to_packets_tb
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avmm_sim_package.h OTHER PATH avmm_sim_package.h
add_fileset_file avs_to_packets_tb.sv SYSTEM_VERILOG PATH avs_to_packets_tb.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL avmm_to_packets_tb
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avmm_sim_package.h OTHER PATH avmm_sim_package.h
add_fileset_file avs_to_packets_tb.sv SYSTEM_VERILOG PATH avs_to_packets_tb.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_160m
set_interface_property avalon_master associatedReset reset_source
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master avmm_readdatavalid readdatavalid Input 1
add_interface_port avalon_master avmm_waitrequest waitrequest Input 1
add_interface_port avalon_master avmm_readdata readdata Input 8
add_interface_port avalon_master avmm_address address Output 24
add_interface_port avalon_master avmm_burstcount burstcount Output 11
add_interface_port avalon_master avmm_byteenable byteenable Output 1
add_interface_port avalon_master avmm_write write Output 1
add_interface_port avalon_master avmm_read read Output 1
add_interface_port avalon_master avmm_writedata writedata Output 8


# 
# connection point reset_source
# 
add_interface reset_source reset start
set_interface_property reset_source associatedClock clock_160m
set_interface_property reset_source associatedDirectReset ""
set_interface_property reset_source associatedResetSinks ""
set_interface_property reset_source synchronousEdges DEASSERT
set_interface_property reset_source ENABLED true
set_interface_property reset_source EXPORT_OF ""
set_interface_property reset_source PORT_NAME_MAP ""
set_interface_property reset_source CMSIS_SVD_VARIABLES ""
set_interface_property reset_source SVD_ADDRESS_GROUP ""

add_interface_port reset_source reset reset Output 1


# 
# connection point clock_50m
# 
add_interface clock_50m clock start
set_interface_property clock_50m associatedDirectClock ""
set_interface_property clock_50m clockRate 0
set_interface_property clock_50m clockRateKnown false
set_interface_property clock_50m ENABLED true
set_interface_property clock_50m EXPORT_OF ""
set_interface_property clock_50m PORT_NAME_MAP ""
set_interface_property clock_50m CMSIS_SVD_VARIABLES ""
set_interface_property clock_50m SVD_ADDRESS_GROUP ""

add_interface_port clock_50m clk_50m clk Output 1


# 
# connection point clock_160m
# 
add_interface clock_160m clock start
set_interface_property clock_160m associatedDirectClock ""
set_interface_property clock_160m clockRate 0
set_interface_property clock_160m clockRateKnown false
set_interface_property clock_160m ENABLED true
set_interface_property clock_160m EXPORT_OF ""
set_interface_property clock_160m PORT_NAME_MAP ""
set_interface_property clock_160m CMSIS_SVD_VARIABLES ""
set_interface_property clock_160m SVD_ADDRESS_GROUP ""

add_interface_port clock_160m clk_160m clk Output 1

