# TCL File Generated by Component Editor 10.0
# Mon Jun 21 13:56:29 MYT 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | checksum "checksum" v1.0
# | null 2010.06.21.13:56:29
# | 
# | 
# | /data/ywgan/checksum_neek/ip/checksum/checksum.v
# | 
# |    ./checksum.v syn, sim
# |    ./mask_acc_fold_32.v syn, sim
# |    ./mask_acc_fold_64.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module checksum
# | 
set_module_property NAME checksum
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Microcore Checksum Accelerator"
set_module_property DISPLAY_NAME "Checksum Calculator"
set_module_property TOP_LEVEL_HDL_FILE checksum.v
set_module_property TOP_LEVEL_HDL_MODULE checksum
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file checksum.v {SYNTHESIS SIMULATION}
add_file mask_acc_fold_32.v {SYNTHESIS SIMULATION}
add_file mask_acc_fold_64.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------


# callbacks
set_module_property ELABORATION_CALLBACK    elaborate_me
set_module_property VALIDATION_CALLBACK     validate_me

# +-----------------------------------
# | parameters
# | 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME "DATA WIDTH"
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES {32 64}
set_parameter_property DATA_WIDTH DISPLAY_HINT ""
set_parameter_property DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property DATA_WIDTH HDL_PARAMETER true

add_parameter SYMBOL_WIDTH INTEGER 8
set_parameter_property SYMBOL_WIDTH DEFAULT_VALUE 8
set_parameter_property SYMBOL_WIDTH DISPLAY_NAME SYMBOL_WIDTH
set_parameter_property SYMBOL_WIDTH TYPE INTEGER
set_parameter_property SYMBOL_WIDTH ENABLED false
set_parameter_property SYMBOL_WIDTH UNITS None
set_parameter_property SYMBOL_WIDTH AFFECTS_GENERATION false
set_parameter_property SYMBOL_WIDTH HDL_PARAMETER true
set_parameter_property SYMBOL_WIDTH VISIBLE false

add_parameter NUMBER_OF_SYMBOLS INTEGER 4
set_parameter_property NUMBER_OF_SYMBOLS DEFAULT_VALUE 4
set_parameter_property NUMBER_OF_SYMBOLS DISPLAY_NAME NUMBER_OF_SYMBOLS
set_parameter_property NUMBER_OF_SYMBOLS TYPE INTEGER
set_parameter_property NUMBER_OF_SYMBOLS ENABLED false
set_parameter_property NUMBER_OF_SYMBOLS UNITS None
set_parameter_property NUMBER_OF_SYMBOLS AFFECTS_GENERATION false
set_parameter_property NUMBER_OF_SYMBOLS HDL_PARAMETER true
set_parameter_property NUMBER_OF_SYMBOLS DERIVED true
set_parameter_property NUMBER_OF_SYMBOLS VISIBLE false

add_parameter NUMBER_OF_SYMBOLS_LOG2 INTEGER 2
set_parameter_property NUMBER_OF_SYMBOLS_LOG2 DEFAULT_VALUE 2
set_parameter_property NUMBER_OF_SYMBOLS_LOG2 DISPLAY_NAME NUMBER_OF_SYMBOLS_LOG2
set_parameter_property NUMBER_OF_SYMBOLS_LOG2 TYPE INTEGER
set_parameter_property NUMBER_OF_SYMBOLS_LOG2 ENABLED false
set_parameter_property NUMBER_OF_SYMBOLS_LOG2 UNITS None
set_parameter_property NUMBER_OF_SYMBOLS_LOG2 AFFECTS_GENERATION false
set_parameter_property NUMBER_OF_SYMBOLS_LOG2 HDL_PARAMETER true
set_parameter_property NUMBER_OF_SYMBOLS_LOG2 DERIVED true
set_parameter_property NUMBER_OF_SYMBOLS_LOG2 VISIBLE false

# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point data_sink
# | 
add_interface data_sink avalon_streaming end
set_interface_property data_sink associatedClock clock_reset
set_interface_property data_sink dataBitsPerSymbol 8
set_interface_property data_sink errorDescriptor ""
set_interface_property data_sink maxChannel 0
set_interface_property data_sink readyLatency 0

set_interface_property data_sink ASSOCIATED_CLOCK clock_reset
set_interface_property data_sink ENABLED true

add_interface_port data_sink snk_data data Input DATA_WIDTH
add_interface_port data_sink snk_valid valid Input 1
add_interface_port data_sink snk_ready ready Output 1
add_interface_port data_sink snk_sop startofpacket Input 1
add_interface_port data_sink snk_eop endofpacket Input 1
add_interface_port data_sink snk_empty empty Input NUMBER_OF_SYMBOLS_LOG2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point result_source
# | 
add_interface result_source avalon_streaming start
set_interface_property result_source associatedClock clock_reset
set_interface_property result_source dataBitsPerSymbol 8
set_interface_property result_source errorDescriptor ""
set_interface_property result_source maxChannel 0
set_interface_property result_source readyLatency 0

set_interface_property result_source ASSOCIATED_CLOCK clock_reset
set_interface_property result_source ENABLED true

add_interface_port result_source src_data data Output 16
add_interface_port result_source src_valid valid Output 1
add_interface_port result_source src_ready ready Input 1
# | 
# +-----------------------------------

proc elaborate_me {}  {
	set_port_property snk_data WIDTH [get_parameter_value DATA_WIDTH]
	set_port_property snk_empty WIDTH [get_parameter_value NUMBER_OF_SYMBOLS_LOG2]
}

proc validate_me {}  {
	set_parameter_value NUMBER_OF_SYMBOLS [expr {[get_parameter_value DATA_WIDTH] / 8}]
  set_parameter_value NUMBER_OF_SYMBOLS_LOG2 [expr {(log([get_parameter_value DATA_WIDTH] / 8) / log(2))}]
}
