set_property SRC_FILE_INFO {cfile:c:/gitlab/NuPRISM/mercury_xu1_pmt/Vivado_PE1/MercuryXU1_PE1.srcs/sources_1/bd/MercuryXU1/ip/MercuryXU1_system_management_wiz_0_0/MercuryXU1_system_management_wiz_0_0.xdc rfile:../../../MercuryXU1_PE1.srcs/sources_1/bd/MercuryXU1/ip/MercuryXU1_system_management_wiz_0_0/MercuryXU1_system_management_wiz_0_0.xdc id:1 order:EARLY scoped_inst:MercuryXU1_i/system_management_wiz_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/gitlab/NuPRISM/mercury_xu1_pmt/src/MercuryXU1_PE1.xdc rfile:../../../../src/MercuryXU1_PE1.xdc id:2} [current_design]
current_instance MercuryXU1_i/system_management_wiz_0/U0
set_property src_info {type:SCOPED_XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD ANALOG [get_ports  vp]
set_property src_info {type:SCOPED_XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD ANALOG [get_ports  vn]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SYSMONE4_X0Y0 [get_cells -hier {*inst_sysmon} -filter {NAME =~ *inst_sysmon}]
current_instance
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE8 [get_ports {Led2_N}]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V3 [get_ports {I2c_Scl}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y7 [get_ports {I2c_Sda}]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG4   [get_ports {IO_B64_AG4}]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG9   [get_ports {IO_B64_AG9}]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH11  [get_ports {IO_B64_AH11}]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ1   [get_ports {IO_B64_AJ1}]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK8   [get_ports {IO_B64_L10_AD4_AK8_N}]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK9   [get_ports {IO_B64_L10_AD4_AK9_P}]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH7   [get_ports {IO_B64_L11_GC_AH7_P}]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ7   [get_ports {IO_B64_L11_GC_AJ7_N}]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG8   [get_ports {IO_B64_L12_GC_AG8_P}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH8   [get_ports {IO_B64_L12_GC_AH8_N}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG5   [get_ports {IO_B64_L13_GC_AG5_N}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG6   [get_ports {IO_B64_L13_GC_AG6_P}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH6   [get_ports {IO_B64_L14_GC_AH6_P}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ6   [get_ports {IO_B64_L14_GC_AJ6_N}]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK6   [get_ports {IO_B64_L15_AD11_AK6_N}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK7   [get_ports {IO_B64_L15_AD11_AK7_P}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF5   [get_ports {IO_B64_L16_AD3_AF5_N}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF6   [get_ports {IO_B64_L16_AD3_AF6_P}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ5   [get_ports {IO_B64_L17_AD10_AJ5_P}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK5   [get_ports {IO_B64_L17_AD10_AK5_N}]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH4   [get_ports {IO_B64_L18_AD2_AH4_P}]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ4   [get_ports {IO_B64_L18_AD2_AJ4_N}]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK3   [get_ports {IO_B64_L19_AD9_AK3_N}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK4   [get_ports {IO_B64_L19_AD9_AK4_P}]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF11  [get_ports {IO_B64_L1_AF11_P}]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG11  [get_ports {IO_B64_L1_AG11_N}]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH2   [get_ports {IO_B64_L20_AD1_AH2_N}]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH3   [get_ports {IO_B64_L20_AD1_AH3_P}]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ2   [get_ports {IO_B64_L21_AD8_AJ2_P}]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK2   [get_ports {IO_B64_L21_AD8_AK2_N}]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG1   [get_ports {IO_B64_L22_AD0_AG1_P}]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH1   [get_ports {IO_B64_L22_AD0_AH1_N}]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF3   [get_ports {IO_B64_L23_AF3_P}]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG3   [get_ports {IO_B64_L23_AG3_N}]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF1   [get_ports {IO_B64_L24_AF1_N}]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF2   [get_ports {IO_B64_L24_AF2_P}]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG13  [get_ports {IO_B64_L2_AG13_P}]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH13  [get_ports {IO_B64_L2_AH13_N}]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH12  [get_ports {IO_B64_L3_AD15_AH12_P}]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ12  [get_ports {IO_B64_L3_AD15_AJ12_N}]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK12  [get_ports {IO_B64_L4_AD7_AK12_N}]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK13  [get_ports {IO_B64_L4_AD7_AK13_P}]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ11  [get_ports {IO_B64_L5_AD14_AJ11_P}]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK11  [get_ports {IO_B64_L5_AD14_AK11_N}]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ10  [get_ports {IO_B64_L6_AD6_AJ10_P}]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK10  [get_ports {IO_B64_L6_AD6_AK10_N}]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF7   [get_ports {IO_B64_L7_AD13_AF7_N}]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF8   [get_ports {IO_B64_L7_AD13_AF8_P}]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF10  [get_ports {IO_B64_L8_AD5_AF10_P}]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG10  [get_ports {IO_B64_L8_AD5_AG10_N}]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH9   [get_ports {IO_B64_L9_AD12_AH9_P}]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ9   [get_ports {IO_B64_L9_AD12_AJ9_N}]
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE1   [get_ports {IO_B65_AE1}]
set_property src_info {type:XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE7   [get_ports {IO_B65_AE7}]
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA7   [get_ports {IO_B65_L10_AD4_AA7_N}]
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8   [get_ports {IO_B65_L10_AD4_AA8_P}]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC7   [get_ports {IO_B65_L11_GC_AC7_P}]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD7   [get_ports {IO_B65_L11_GC_AD7_N}]
set_property src_info {type:XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8   [get_ports {IO_B65_L12_GC_AB8_P}]
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC8   [get_ports {IO_B65_L12_GC_AC8_N}]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB5   [get_ports {IO_B65_L13_GC_AB5_N}]
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB6   [get_ports {IO_B65_L13_GC_AB6_P}]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC6   [get_ports {IO_B65_L14_GC_AC6_P}]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD6   [get_ports {IO_B65_L14_GC_AD6_N}]
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA5   [get_ports {IO_B65_L15_AD11_AA5_N}]
set_property src_info {type:XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA6   [get_ports {IO_B65_L15_AD11_AA6_P}]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD5   [get_ports {IO_B65_L16_AD3_AD5_P}]
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE5   [get_ports {IO_B65_L16_AD3_AE5_N}]
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD4   [get_ports {IO_B65_L17_AD10_AD4_P}]
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE4   [get_ports {IO_B65_L17_AD10_AE4_N}]
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB4   [get_ports {IO_B65_L18_AD2_AB4_P}]
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC4   [get_ports {IO_B65_L18_AD2_AC4_N}]
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB3   [get_ports {IO_B65_L19_AD9_AB3_P}]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC3   [get_ports {IO_B65_L19_AD9_AC3_N}]
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB13  [get_ports {IO_B65_L1_AB13_P}]
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC13  [get_ports {IO_B65_L1_AC13_N}]
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE2   [get_ports {IO_B65_L20_AD1_AE2_N}]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE3   [get_ports {IO_B65_L20_AD1_AE3_P}]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC2   [get_ports {IO_B65_L21_AD8_AC2_P}]
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD2   [get_ports {IO_B65_L21_AD8_AD2_N}]
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC1   [get_ports {IO_B65_L22_AD0_AC1_P}]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD1   [get_ports {IO_B65_L22_AD0_AD1_N}]
set_property src_info {type:XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA2   [get_ports {IO_B65_L23_AA2_N}]
set_property src_info {type:XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA3   [get_ports {IO_B65_L23_SCLK_AA3_P}]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB1   [get_ports {IO_B65_L24_PERST_AB1_N_n}]
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA1   [get_ports {IO_B65_L24_SDA_AA1_P}]
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE13  [get_ports {IO_B65_L2_AE13_P}]
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF13  [get_ports {IO_B65_L2_AF13_N}]
set_property src_info {type:XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD12  [get_ports {IO_B65_L3_AD15_AD12_P}]
set_property src_info {type:XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE12  [get_ports {IO_B65_L3_AD15_AE12_N}]
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC11  [get_ports {IO_B65_L4_AD7_AC11_P}]
set_property src_info {type:XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD11  [get_ports {IO_B65_L4_AD7_AD11_N}]
set_property src_info {type:XDC file:2 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA11  [get_ports {IO_B65_L5_AD14_AA11_N}]
set_property src_info {type:XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA12  [get_ports {IO_B65_L5_AD14_AA12_P}]
set_property src_info {type:XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB10  [get_ports {IO_B65_L6_AD6_AB10_N}]
set_property src_info {type:XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB11  [get_ports {IO_B65_L6_AD6_AB11_P}]
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB9   [get_ports {IO_B65_L7_AD13_AB9_P}]
set_property src_info {type:XDC file:2 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC9   [get_ports {IO_B65_L7_AD13_AC9_N}]
set_property src_info {type:XDC file:2 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD10  [get_ports {IO_B65_L8_AD5_AD10_P}]
set_property src_info {type:XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE10  [get_ports {IO_B65_L8_AD5_AE10_N}]
set_property src_info {type:XDC file:2 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD9   [get_ports {IO_B65_L9_AD12_AD9_P}]
set_property src_info {type:XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE9   [get_ports {IO_B65_L9_AD12_AE9_N}]
set_property src_info {type:XDC file:2 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6   [get_ports {IO_B66_L10_AD4_U6_N}]
set_property src_info {type:XDC file:2 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7   [get_ports {IO_B66_L10_AD4_U7_P}]
set_property src_info {type:XDC file:2 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6   [get_ports {IO_B66_L11_GC_V6_N}]
set_property src_info {type:XDC file:2 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7   [get_ports {IO_B66_L11_GC_V7_P}]
set_property src_info {type:XDC file:2 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6   [get_ports {IO_B66_L12_GC_W6_N}]
set_property src_info {type:XDC file:2 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W7   [get_ports {IO_B66_L12_GC_W7_P}]
set_property src_info {type:XDC file:2 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U8   [get_ports {IO_B66_L13_GC_U8_P}]
set_property src_info {type:XDC file:2 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8   [get_ports {IO_B66_L13_GC_V8_N}]
set_property src_info {type:XDC file:2 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8   [get_ports {IO_B66_L14_GC_Y8_N}]
set_property src_info {type:XDC file:2 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9   [get_ports {IO_B66_L14_GC_Y9_P}]
set_property src_info {type:XDC file:2 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U11  [get_ports {IO_B66_L15_AD11_U11_P}]
set_property src_info {type:XDC file:2 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V11  [get_ports {IO_B66_L15_AD11_V11_N}]
set_property src_info {type:XDC file:2 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W10  [get_ports {IO_B66_L16_AD3_W10_N}]
set_property src_info {type:XDC file:2 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W11  [get_ports {IO_B66_L16_AD3_W11_P}]
set_property src_info {type:XDC file:2 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9   [get_ports {IO_B66_L17_AD10_U9_P}]
set_property src_info {type:XDC file:2 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9   [get_ports {IO_B66_L17_AD10_V9_N}]
set_property src_info {type:XDC file:2 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T11  [get_ports {IO_B66_L18_AD2_T11_P}]
set_property src_info {type:XDC file:2 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U10  [get_ports {IO_B66_L18_AD2_U10_N}]
set_property src_info {type:XDC file:2 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T10  [get_ports {IO_B66_L19_AD9_T10_N}]
set_property src_info {type:XDC file:2 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R10  [get_ports {IO_B66_L19_AD9_R10_P}]
set_property src_info {type:XDC file:2 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y3   [get_ports {IO_B66_L1_Y3_N}]
set_property src_info {type:XDC file:2 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y4   [get_ports {IO_B66_L1_Y4_P}]
set_property src_info {type:XDC file:2 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P10  [get_ports {IO_B66_L20_AD1_P10_N}]
set_property src_info {type:XDC file:2 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P11  [get_ports {IO_B66_L20_AD1_P11_P}]
set_property src_info {type:XDC file:2 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M12  [get_ports {IO_B66_L21_AD8_M12_N}]
set_property src_info {type:XDC file:2 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N12  [get_ports {IO_B66_L21_AD8_N12_P}]
set_property src_info {type:XDC file:2 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M10  [get_ports {IO_B66_L22_AD0_M10_N}]
set_property src_info {type:XDC file:2 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N10  [get_ports {IO_B66_L22_AD0_N10_P}]
set_property src_info {type:XDC file:2 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L11  [get_ports {IO_B66_L23_L11_N}]
set_property src_info {type:XDC file:2 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L12  [get_ports {IO_B66_L23_L12_P}]
set_property src_info {type:XDC file:2 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K10  [get_ports {IO_B66_L24_K10_N}]
set_property src_info {type:XDC file:2 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L10  [get_ports {IO_B66_L24_L10_P}]
set_property src_info {type:XDC file:2 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y1   [get_ports {IO_B66_L2_Y1_N}]
set_property src_info {type:XDC file:2 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y2   [get_ports {IO_B66_L2_Y2_P}]
set_property src_info {type:XDC file:2 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W1   [get_ports {IO_B66_L3_AD15_W1_N}]
set_property src_info {type:XDC file:2 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W2   [get_ports {IO_B66_L3_AD15_W2_P}]
set_property src_info {type:XDC file:2 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1   [get_ports {IO_B66_L4_AD7_V1_N}]
set_property src_info {type:XDC file:2 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2   [get_ports {IO_B66_L4_AD7_V2_P}]
set_property src_info {type:XDC file:2 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2   [get_ports {IO_B66_L5_AD14_U2_P}]
set_property src_info {type:XDC file:2 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3   [get_ports {IO_B66_L5_AD14_U3_N}]
set_property src_info {type:XDC file:2 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1   [get_ports {IO_B66_L6_AD6_T1_P}]
set_property src_info {type:XDC file:2 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1   [get_ports {IO_B66_L6_AD6_U1_N}]
set_property src_info {type:XDC file:2 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5   [get_ports {IO_B66_L7_AD13_W5_P}]
set_property src_info {type:XDC file:2 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y5   [get_ports {IO_B66_L7_AD13_Y5_N}]
set_property src_info {type:XDC file:2 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4   [get_ports {IO_B66_L8_AD5_V4_P}]
set_property src_info {type:XDC file:2 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W4   [get_ports {IO_B66_L8_AD5_W4_N}]
set_property src_info {type:XDC file:2 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4   [get_ports {IO_B66_L9_AD12_U4_N}]
set_property src_info {type:XDC file:2 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5   [get_ports {IO_B66_L9_AD12_U5_P}]
set_property src_info {type:XDC file:2 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N11  [get_ports {IO_B66_N11}]
set_property src_info {type:XDC file:2 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y10  [get_ports {IO_B66_Y10}]
set_property src_info {type:XDC file:2 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G11  [get_ports {IO_B48_L10_AD10_G11_N}]
set_property src_info {type:XDC file:2 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H12  [get_ports {IO_B48_L10_AD10_H12_P}]
set_property src_info {type:XDC file:2 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H11  [get_ports {IO_B48_L11_AD9_H11_N}]
set_property src_info {type:XDC file:2 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J12  [get_ports {IO_B48_L11_AD9_J12_P}]
set_property src_info {type:XDC file:2 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J10  [get_ports {IO_B48_L12_AD8_J10_N}]
set_property src_info {type:XDC file:2 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J11  [get_ports {IO_B48_L12_AD8_J11_P}]
set_property src_info {type:XDC file:2 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B11  [get_ports {IO_B48_L1_AD15_B11_N}]
set_property src_info {type:XDC file:2 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12  [get_ports {IO_B48_L1_AD15_C12_P}]
set_property src_info {type:XDC file:2 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A11  [get_ports {IO_B48_L2_AD14_A11_N}]
set_property src_info {type:XDC file:2 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A12  [get_ports {IO_B48_L2_AD14_A12_P}]
set_property src_info {type:XDC file:2 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A10  [get_ports {IO_B48_L3_AD13_A10_N}]
set_property src_info {type:XDC file:2 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B10  [get_ports {IO_B48_L3_AD13_B10_P}]
set_property src_info {type:XDC file:2 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C11  [get_ports {IO_B48_L4_AD12_C11_N}]
set_property src_info {type:XDC file:2 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D11  [get_ports {IO_B48_L4_AD12_D11_P}]
set_property src_info {type:XDC file:2 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D12  [get_ports {IO_B48_L5_HDGC_D12_N}]
set_property src_info {type:XDC file:2 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12  [get_ports {IO_B48_L5_HDGC_E12_P}]
set_property src_info {type:XDC file:2 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D10  [get_ports {IO_B48_L6_HDGC_D10_N}]
set_property src_info {type:XDC file:2 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E10  [get_ports {IO_B48_L6_HDGC_E10_P}]
set_property src_info {type:XDC file:2 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F11  [get_ports {IO_B48_L7_HDGC_F11_N}]
set_property src_info {type:XDC file:2 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F12  [get_ports {IO_B48_L7_HDGC_F12_P}]
set_property src_info {type:XDC file:2 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F10  [get_ports {IO_B48_L8_HDGC_F10_N}]
set_property src_info {type:XDC file:2 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G10  [get_ports {IO_B48_L8_HDGC_G10_P}]
set_property src_info {type:XDC file:2 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12  [get_ports {IO_B48_L9_AD11_K12_N}]
set_property src_info {type:XDC file:2 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13  [get_ports {IO_B48_L9_AD11_K13_P}]
set_property src_info {type:XDC file:2 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15  [get_ports {IO_B47_L10_AD2_J15_N}]
set_property src_info {type:XDC file:2 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15  [get_ports {IO_B47_L10_AD2_K15_P}]
set_property src_info {type:XDC file:2 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J14  [get_ports {IO_B47_L11_AD1_J14_N}]
set_property src_info {type:XDC file:2 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K14  [get_ports {IO_B47_L11_AD1_K14_P}]
set_property src_info {type:XDC file:2 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H13  [get_ports {IO_B47_L12_AD0_H13_N}]
set_property src_info {type:XDC file:2 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14  [get_ports {IO_B47_L12_AD0_H14_P}]
set_property src_info {type:XDC file:2 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15  [get_ports {IO_B47_L1_AD11_A15_N}]
set_property src_info {type:XDC file:2 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15  [get_ports {IO_B47_L1_AD11_B15_P}]
set_property src_info {type:XDC file:2 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14  [get_ports {IO_B47_L2_AD10_A14_N}]
set_property src_info {type:XDC file:2 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B14  [get_ports {IO_B47_L2_AD10_B14_P}]
set_property src_info {type:XDC file:2 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A13  [get_ports {IO_B47_L3_AD9_A13_N}]
set_property src_info {type:XDC file:2 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B13  [get_ports {IO_B47_L3_AD9_B13_P}]
set_property src_info {type:XDC file:2 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C13  [get_ports {IO_B47_L4_AD8_C13_N}]
set_property src_info {type:XDC file:2 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C14  [get_ports {IO_B47_L4_AD8_C14_P}]
set_property src_info {type:XDC file:2 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14  [get_ports {IO_B47_L5_HDGC_AD7_D14_N}]
set_property src_info {type:XDC file:2 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D15  [get_ports {IO_B47_L5_HDGC_AD7_D15_P}]
set_property src_info {type:XDC file:2 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13  [get_ports {IO_B47_L6_HDGC_AD6_E13_N}]
set_property src_info {type:XDC file:2 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E14  [get_ports {IO_B47_L6_HDGC_AD6_E14_P}]
set_property src_info {type:XDC file:2 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15  [get_ports {IO_B47_L7_HDGC_AD5_E15_N}]
set_property src_info {type:XDC file:2 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15  [get_ports {IO_B47_L7_HDGC_AD5_F15_P}]
set_property src_info {type:XDC file:2 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13  [get_ports {IO_B47_L8_HDGC_AD4_F13_N}]
set_property src_info {type:XDC file:2 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13  [get_ports {IO_B47_L8_HDGC_AD4_G13_P}]
set_property src_info {type:XDC file:2 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14  [get_ports {IO_B47_L9_AD3_G14_N}]
set_property src_info {type:XDC file:2 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15  [get_ports {IO_B47_L9_AD3_G15_P}]
