# TCL File Generated by Component Editor 12.1sp1
# Wed Sep 18 16:35:00 PDT 2013
# DO NOT MODIFY


# 
# dual_port_mem_controller_qsys "dual_port_mem_controller_qsys" v1.0
# Yair Linn 2013.09.18.16:35:00
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module dual_port_mem_controller_qsys
# 
set_module_property NAME dual_port_mem_controller_qsys
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Memories and Memory Controllers/On-Chip"
set_module_property AUTHOR "Yair Linn"
set_module_property DISPLAY_NAME dual_port_mem_controller_qsys
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dual_port_memory_controller_avalon_mm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dual_port_memory_controller_avalon_mm.v VERILOG PATH dual_port_memory_controller_avalon_mm.v


# 
# parameters
# 
add_parameter num_addr_bits INTEGER 12
set_parameter_property num_addr_bits DEFAULT_VALUE 12
set_parameter_property num_addr_bits DISPLAY_NAME num_addr_bits
set_parameter_property num_addr_bits TYPE INTEGER
set_parameter_property num_addr_bits UNITS None
set_parameter_property num_addr_bits ALLOWED_RANGES -2147483648:2147483647
set_parameter_property num_addr_bits HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 3
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 5
set_interface_property avalon_slave_0 readWaitTime 5
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitStates 5
set_interface_property avalon_slave_0 writeWaitTime 5
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 address address Input num_addr_bits
add_interface_port avalon_slave_0 read_data readdata Output 32
add_interface_port avalon_slave_0 write_data writedata Input 32
add_interface_port avalon_slave_0 read_now read Input 1
add_interface_port avalon_slave_0 write_now write Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end addr_to_dp_ram export Output num_addr_bits
add_interface_port conduit_end data_from_dp_ram export Input 32
add_interface_port conduit_end data_to_dp_ram export Output 32
add_interface_port conduit_end clk_to_dp_ram export Output 1
add_interface_port conduit_end write_en export Output 1
add_interface_port conduit_end read_en export Output 1

