# TCL File Generated by Component Editor 14.1
# Mon Aug 28 23:18:45 PDT 2017
# DO NOT MODIFY


# 
# freq_counter_64bit "freq_counter_64bit" v2.0
# Yair Linn 2017.08.28.23:18:45
# This is a 64 bit counter that counts up every clock cycle, with a reference count. Address 0 is lower 32 bits, address 1 is upper 32 bits, address 2 is reference count lower 32 bits, , address 3 is reference count upper 32 bits.
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.1


# 
# module freq_counter_64bit
# 
set_module_property DESCRIPTION "This is a 64 bit counter that counts up every clock cycle, with a reference count. Address 0 is lower 32 bits, address 1 is upper 32 bits, address 2 is reference count lower 32 bits, , address 3 is reference count upper 32 bits."
set_module_property NAME freq_counter_64bit
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Peripherals
set_module_property AUTHOR "Yair Linn"
set_module_property DISPLAY_NAME freq_counter_64bit
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL freq_counter_64bit
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property quartus_synth ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file freq_counter_64bit.v VERILOG PATH freq_counter_64bit.v

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog TOP_LEVEL freq_counter_64bit
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property sim_verilog ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file freq_counter_64bit.v VERILOG PATH freq_counter_64bit.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_reset
# 
add_interface clock_reset clock end
set_interface_property clock_reset clockRate 0
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset clk clk Input 1


# 
# connection point ref_clock_reset
# 
add_interface ref_clock_reset clock end
set_interface_property ref_clock_reset clockRate 0
set_interface_property ref_clock_reset ENABLED true
set_interface_property ref_clock_reset EXPORT_OF ""
set_interface_property ref_clock_reset PORT_NAME_MAP ""
set_interface_property ref_clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property ref_clock_reset SVD_ADDRESS_GROUP ""

add_interface_port ref_clock_reset reference_and_avalon_mm_clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock ref_clock_reset
set_interface_property avalon_slave_0 associatedReset ref_reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 5
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 5
set_interface_property avalon_slave_0 readWaitTime 5
set_interface_property avalon_slave_0 setupTime 5
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitStates 5
set_interface_property avalon_slave_0 writeWaitTime 5
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 read_data readdata Output 32
add_interface_port avalon_slave_0 read_now read Input 1
add_interface_port avalon_slave_0 write_now write Input 1
add_interface_port avalon_slave_0 write_data writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_reset
set_interface_property reset synchronousEdges BOTH
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point ref_reset
# 
add_interface ref_reset reset end
set_interface_property ref_reset associatedClock ref_clock_reset
set_interface_property ref_reset synchronousEdges BOTH
set_interface_property ref_reset ENABLED true
set_interface_property ref_reset EXPORT_OF ""
set_interface_property ref_reset PORT_NAME_MAP ""
set_interface_property ref_reset CMSIS_SVD_VARIABLES ""
set_interface_property ref_reset SVD_ADDRESS_GROUP ""

add_interface_port ref_reset reference_and_avalon_mm_reset reset Input 1


# 
# connection point current_count
# 
add_interface current_count conduit end
set_interface_property current_count associatedClock clock_reset
set_interface_property current_count associatedReset reset
set_interface_property current_count ENABLED true
set_interface_property current_count EXPORT_OF ""
set_interface_property current_count PORT_NAME_MAP ""
set_interface_property current_count CMSIS_SVD_VARIABLES ""
set_interface_property current_count SVD_ADDRESS_GROUP ""

add_interface_port current_count the_counter export Output 64


# 
# connection point ref_count
# 
add_interface ref_count conduit end
set_interface_property ref_count associatedClock ref_clock_reset
set_interface_property ref_count associatedReset ref_reset
set_interface_property ref_count ENABLED true
set_interface_property ref_count EXPORT_OF ""
set_interface_property ref_count PORT_NAME_MAP ""
set_interface_property ref_count CMSIS_SVD_VARIABLES ""
set_interface_property ref_count SVD_ADDRESS_GROUP ""

add_interface_port ref_count ref_counter export Output 64

