# TCL File Generated by Component Editor 13.0
# Mon Aug 12 00:00:29 CDT 2013
# DO NOT MODIFY


# 
# enc_data_gen "enc_data_gen" v1.0
#  2013.08.12.00:00:28
# 
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module enc_data_gen
# 
set_module_property DESCRIPTION ""
set_module_property NAME enc_data_gen
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME enc_data_gen
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL enc_data_gen_gz
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file jesdcon_pkg.v VERILOG PATH ../src/jesdcon_pkg.v
add_fileset_file enc_data_gen_gz.sv SYSTEM_VERILOG PATH enc_data_gen_gz.sv TOP_LEVEL_FILE
#add_fileset_file jesdcon_pkg.v VERILOG PATH ../src/jesdcon_pkg.v

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog TOP_LEVEL enc_data_gen_gz
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file jesdcon_pkg.v VERILOG PATH ../src/jesdcon_pkg.v
add_fileset_file enc_data_gen_gz.sv SYSTEM_VERILOG PATH enc_data_gen_gz.sv


# 
# parameters
# 
add_parameter M INTEGER 2
set_parameter_property M DEFAULT_VALUE 2
set_parameter_property M DISPLAY_NAME M
set_parameter_property M TYPE INTEGER
set_parameter_property M UNITS None
set_parameter_property M ALLOWED_RANGES -2147483648:2147483647
set_parameter_property M HDL_PARAMETER true
add_parameter S INTEGER 1
set_parameter_property S DEFAULT_VALUE 1
set_parameter_property S DISPLAY_NAME S
set_parameter_property S TYPE INTEGER
set_parameter_property S UNITS None
set_parameter_property S ALLOWED_RANGES -2147483648:2147483647
set_parameter_property S HDL_PARAMETER true
add_parameter SAMPLES_PER_CLK INTEGER 1
set_parameter_property SAMPLES_PER_CLK DEFAULT_VALUE 1
set_parameter_property SAMPLES_PER_CLK DISPLAY_NAME SAMPLES_PER_CLK
set_parameter_property SAMPLES_PER_CLK TYPE INTEGER
set_parameter_property SAMPLES_PER_CLK UNITS None
set_parameter_property SAMPLES_PER_CLK ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SAMPLES_PER_CLK HDL_PARAMETER true
add_parameter RD_ADDR_WIDTH INTEGER 13
set_parameter_property RD_ADDR_WIDTH DEFAULT_VALUE 13
set_parameter_property RD_ADDR_WIDTH DISPLAY_NAME RD_ADDR_WIDTH
set_parameter_property RD_ADDR_WIDTH TYPE INTEGER
set_parameter_property RD_ADDR_WIDTH UNITS None
set_parameter_property RD_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RD_ADDR_WIDTH HDL_PARAMETER true
add_parameter PRBS_L INTEGER 16
set_parameter_property PRBS_L DEFAULT_VALUE 16
set_parameter_property PRBS_L DISPLAY_NAME PRBS_L
set_parameter_property PRBS_L TYPE INTEGER
set_parameter_property PRBS_L UNITS None
set_parameter_property PRBS_L ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PRBS_L HDL_PARAMETER true
add_parameter PRBS_M INTEGER 9
set_parameter_property PRBS_M DEFAULT_VALUE 9
set_parameter_property PRBS_M DISPLAY_NAME PRBS_M
set_parameter_property PRBS_M TYPE INTEGER
set_parameter_property PRBS_M UNITS None
set_parameter_property PRBS_M ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PRBS_M HDL_PARAMETER true
add_parameter PRBS_N INTEGER 5
set_parameter_property PRBS_N DEFAULT_VALUE 5
set_parameter_property PRBS_N DISPLAY_NAME PRBS_N
set_parameter_property PRBS_N TYPE INTEGER
set_parameter_property PRBS_N UNITS None
set_parameter_property PRBS_N ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PRBS_N HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1

# 
# connection point clock_mem
# 
add_interface clock_mem clock end
set_interface_property clock_mem clockRate 0
set_interface_property clock_mem ENABLED true
set_interface_property clock_mem EXPORT_OF ""
set_interface_property clock_mem PORT_NAME_MAP ""
set_interface_property clock_mem SVD_ADDRESS_GROUP ""

add_interface_port clock_mem clk_mem clk Input 1

# 
# connection point clock_100
# 
add_interface clock_100 clock end
set_interface_property clock_100 clockRate 0
set_interface_property clock_100 ENABLED true
set_interface_property clock_100 EXPORT_OF ""
set_interface_property clock_100 PORT_NAME_MAP ""
set_interface_property clock_100 SVD_ADDRESS_GROUP ""

add_interface_port clock_100 clk_100 clk Input 1


# 
# connection point reset_sink_0
# 
add_interface reset_sink_0 reset end
set_interface_property reset_sink_0 associatedClock clock
set_interface_property reset_sink_0 synchronousEdges DEASSERT
set_interface_property reset_sink_0 ENABLED true
set_interface_property reset_sink_0 EXPORT_OF ""
set_interface_property reset_sink_0 PORT_NAME_MAP ""
set_interface_property reset_sink_0 SVD_ADDRESS_GROUP ""

add_interface_port reset_sink_0 rstn reset_n Input 1


# 
# connection point reset_sink_mem
# 
add_interface reset_sink_mem reset end
set_interface_property reset_sink_mem associatedClock clock_mem
set_interface_property reset_sink_mem synchronousEdges DEASSERT
set_interface_property reset_sink_mem ENABLED true
set_interface_property reset_sink_mem EXPORT_OF ""
set_interface_property reset_sink_mem PORT_NAME_MAP ""
set_interface_property reset_sink_mem SVD_ADDRESS_GROUP ""

add_interface_port reset_sink_mem rstn_mem reset_n Input 1


# 
# connection point reset_sink_100
# 
add_interface reset_sink_100 reset end
set_interface_property reset_sink_100 associatedClock clock_100
set_interface_property reset_sink_100 synchronousEdges DEASSERT
set_interface_property reset_sink_100 ENABLED true
set_interface_property reset_sink_100 EXPORT_OF ""
set_interface_property reset_sink_100 PORT_NAME_MAP ""
set_interface_property reset_sink_100 SVD_ADDRESS_GROUP ""

add_interface_port reset_sink_100 rstn_100 reset_n Input 1




# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_100
set_interface_property avalon_slave_0 associatedReset reset_sink_100
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 2
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 wbyteenable byteenable Input 4
add_interface_port avalon_slave_0 avmm_addr address Input 16
add_interface_port avalon_slave_0 avmm_datain writedata Input 32
add_interface_port avalon_slave_0 avmm_dataout readdata Output 32
add_interface_port avalon_slave_0 avmm_write_en write Input 1
add_interface_port avalon_slave_0 avmm_read_en read Input 1
#add_interface_port avalon_slave_0 avmm_rddata_valid readdatavalid Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset_sink_0
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source avst_data data Output M*16*SAMPLES_PER_CLK*S
add_interface_port avalon_streaming_source avst_ready ready Input 1
add_interface_port avalon_streaming_source avst_valid valid Output 1


# 
# connection point scope_trig
# 
add_interface scope_trig conduit end
set_interface_property scope_trig associatedClock ""
set_interface_property scope_trig associatedReset ""
set_interface_property scope_trig ENABLED true
set_interface_property scope_trig EXPORT_OF ""
set_interface_property scope_trig PORT_NAME_MAP ""
set_interface_property scope_trig SVD_ADDRESS_GROUP ""

add_interface_port scope_trig scope_trig export Output 1


# 
# connection point m1
# 
add_interface m1 avalon start
set_interface_property m1 addressUnits WORDS
set_interface_property m1 associatedClock clock_mem
set_interface_property m1 associatedReset reset_sink_mem
set_interface_property m1 bitsPerSymbol 8
set_interface_property m1 burstOnBurstBoundariesOnly false
set_interface_property m1 burstcountUnits WORDS
set_interface_property m1 doStreamReads false
set_interface_property m1 doStreamWrites false
set_interface_property m1 holdTime 0
set_interface_property m1 linewrapBursts false
set_interface_property m1 maximumPendingReadTransactions 32
set_interface_property m1 readLatency 0
set_interface_property m1 readWaitTime 0
set_interface_property m1 setupTime 0
set_interface_property m1 timingUnits Cycles
set_interface_property m1 writeWaitTime 0
set_interface_property m1 ENABLED true
set_interface_property m1 EXPORT_OF ""
set_interface_property m1 PORT_NAME_MAP ""
set_interface_property m1 SVD_ADDRESS_GROUP ""

add_interface_port m1 mem_avm_m1_read read Output 1
add_interface_port m1 mem_avm_m1_waitrequest waitrequest Input 1
add_interface_port m1 mem_avm_m1_readdata readdata Input M*SAMPLES_PER_CLK*16
add_interface_port m1 mem_avm_m1_write write Output 1
add_interface_port m1 mem_avm_m1_writedata writedata Output M*SAMPLES_PER_CLK*16
add_interface_port m1 mem_avm_m1_readdatavalid readdatavalid Input 1
add_interface_port m1 mem_avm_m1_address address Output 27
add_interface_port m1 mem_avm_m1_burstcount burstcount Output 4


# 
# connection point m2
# 
add_interface m2 avalon start
set_interface_property m2 addressUnits WORDS
set_interface_property m2 associatedClock clock_mem
set_interface_property m2 associatedReset reset_sink_mem
set_interface_property m2 bitsPerSymbol 8
set_interface_property m2 burstOnBurstBoundariesOnly false
set_interface_property m2 burstcountUnits WORDS
set_interface_property m2 doStreamReads false
set_interface_property m2 doStreamWrites false
set_interface_property m2 holdTime 0
set_interface_property m2 linewrapBursts false
set_interface_property m2 maximumPendingReadTransactions 32
set_interface_property m2 readLatency 0
set_interface_property m2 readWaitTime 0
set_interface_property m2 setupTime 0
set_interface_property m2 timingUnits Cycles
set_interface_property m2 writeWaitTime 0
set_interface_property m2 ENABLED true
set_interface_property m2 EXPORT_OF ""
set_interface_property m2 PORT_NAME_MAP ""
set_interface_property m2 SVD_ADDRESS_GROUP ""

add_interface_port m2 mem_avm_m2_read read Output 1
add_interface_port m2 mem_avm_m2_waitrequest waitrequest Input 1
add_interface_port m2 mem_avm_m2_readdata readdata Input M*SAMPLES_PER_CLK*16
add_interface_port m2 mem_avm_m2_write write Output 1
add_interface_port m2 mem_avm_m2_writedata writedata Output M*SAMPLES_PER_CLK*16
add_interface_port m2 mem_avm_m2_readdatavalid readdatavalid Input 1
add_interface_port m2 mem_avm_m2_address address Output 27
add_interface_port m2 mem_avm_m2_burstcount burstcount Output 4


# 
# connection point tx_ready
# 
add_interface tx_ready conduit end
set_interface_property tx_ready associatedClock ""
set_interface_property tx_ready associatedReset ""
set_interface_property tx_ready ENABLED true
set_interface_property tx_ready EXPORT_OF ""
set_interface_property tx_ready PORT_NAME_MAP ""
set_interface_property tx_ready SVD_ADDRESS_GROUP ""

add_interface_port tx_ready tx_ready tx_ready Input 1

# 
# connection point jesd_tx_M
# 
add_interface jesd_tx_M conduit end
set_interface_property jesd_tx_M associatedClock ""
set_interface_property jesd_tx_M associatedReset ""
set_interface_property jesd_tx_M ENABLED true
set_interface_property jesd_tx_M EXPORT_OF ""
set_interface_property jesd_tx_M PORT_NAME_MAP ""
set_interface_property jesd_tx_M SVD_ADDRESS_GROUP ""

add_interface_port jesd_tx_M jesd_tx_M jesd_tx_M Input 2
