# (C) 2001-2017 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 14.1
# Tue Jul 15 13:02:33 MYT 2014
# DO NOT MODIFY


# 
# soft_asmiblock "Altera SOFT_ASMIBLOCK" v14.1
# Altera Corporation 2014.07.15.13:02:33
# This component connects to Altera EPCQ controller so that the QSPI signal can be used as general purpose pin
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.1


# 
# module soft_asmiblock
# 
set_module_property DESCRIPTION "This component connects to Altera EPCQ controller so that the QSPI signal can be used as general purpose pin"
set_module_property NAME soft_asmiblock
set_module_property VERSION 14.1
set_module_property INTERNAL true
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Basic Functions/Configuration and Programming"
set_module_property AUTHOR "Altera Corporation"
set_module_property DISPLAY_NAME "Altera SOFT ASMIBLOCK"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property HIDE_FROM_QUARTUS true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL soft_asmiblock
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file soft_asmiblock.sv SYSTEM_VERILOG PATH soft_asmiblock.sv TOP_LEVEL_FILE
add_fileset_file soft_asmiblock.sv SYSTEM_VERILOG PATH soft_asmiblock.sv 

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL soft_asmiblock
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file soft_asmiblock.sv SYSTEM_VERILOG PATH soft_asmiblock.sv TOP_LEVEL_FILE
add_fileset_file soft_asmiblock.sv SYSTEM_VERILOG PATH soft_asmiblock.sv


# 
# parameters
#
add_parameter IO_MODE STRING "STANDARD"
set_parameter_property IO_MODE DISPLAY_NAME "Choose I/O mode"
set_parameter_property IO_MODE ALLOWED_RANGES {"STANDARD" "QUAD"}
set_parameter_property IO_MODE DESCRIPTION "Select extended data width when Fast Read operation is enabled"
set_parameter_property IO_MODE HDL_PARAMETER true

add_parameter CS_WIDTH INTEGER 1
set_parameter_property CS_WIDTH DEFAULT_VALUE 1
set_parameter_property CS_WIDTH DISPLAY_NAME CS_WIDTH
set_parameter_property CS_WIDTH DERIVED true
set_parameter_property CS_WIDTH TYPE INTEGER
set_parameter_property CS_WIDTH VISIBLE false
set_parameter_property CS_WIDTH UNITS None
set_parameter_property CS_WIDTH ALLOWED_RANGES {1:1, 3}
set_parameter_property CS_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point dclk
# 
add_interface dclk conduit end
set_interface_property dclk associatedClock ""
set_interface_property dclk associatedReset ""
set_interface_property dclk ENABLED true
set_interface_property dclk EXPORT_OF ""
set_interface_property dclk PORT_NAME_MAP ""
set_interface_property dclk CMSIS_SVD_VARIABLES ""
set_interface_property dclk SVD_ADDRESS_GROUP ""

add_interface_port dclk dclk conduit_dclk Input 1


# 
# connection point sce
# 
add_interface sce conduit end
set_interface_property sce associatedClock ""
set_interface_property sce associatedReset ""
set_interface_property sce ENABLED true
set_interface_property sce EXPORT_OF ""
set_interface_property sce PORT_NAME_MAP ""
set_interface_property sce CMSIS_SVD_VARIABLES ""
set_interface_property sce SVD_ADDRESS_GROUP ""

add_interface_port sce sce conduit_scein Input CS_WIDTH


# 
# connection point dataout
# 
add_interface dataout conduit end
set_interface_property dataout associatedClock ""
set_interface_property dataout associatedReset ""
set_interface_property dataout ENABLED true
set_interface_property dataout EXPORT_OF ""
set_interface_property dataout PORT_NAME_MAP ""
set_interface_property dataout CMSIS_SVD_VARIABLES ""
set_interface_property dataout SVD_ADDRESS_GROUP ""

add_interface_port dataout dataout conduit_sdoin Input 4


# 
# connection point dataoe
# 
add_interface dataoe conduit end
set_interface_property dataoe associatedClock ""
set_interface_property dataoe associatedReset ""
set_interface_property dataoe ENABLED true
set_interface_property dataoe EXPORT_OF ""
set_interface_property dataoe PORT_NAME_MAP ""
set_interface_property dataoe CMSIS_SVD_VARIABLES ""
set_interface_property dataoe SVD_ADDRESS_GROUP ""

add_interface_port dataoe dataoe conduit_dataoe Input 4


# 
# connection point datain
# 
add_interface datain conduit end
set_interface_property datain associatedClock ""
set_interface_property datain associatedReset ""
set_interface_property datain ENABLED true
set_interface_property datain EXPORT_OF ""
set_interface_property datain PORT_NAME_MAP ""
set_interface_property datain CMSIS_SVD_VARIABLES ""
set_interface_property datain SVD_ADDRESS_GROUP ""

add_interface_port datain datain conduit_dataout Output 4


# 
# connection point dclk_out
# 
add_interface dclk_out conduit end
set_interface_property dclk_out associatedClock ""
set_interface_property dclk_out associatedReset ""
set_interface_property dclk_out ENABLED true
set_interface_property dclk_out EXPORT_OF ""
set_interface_property dclk_out PORT_NAME_MAP ""
set_interface_property dclk_out CMSIS_SVD_VARIABLES ""
set_interface_property dclk_out SVD_ADDRESS_GROUP ""

add_interface_port dclk_out dclk_out conduit_dclk_out Output 1


# 
# connection point ncs
# 
add_interface ncs conduit end
set_interface_property ncs associatedClock ""
set_interface_property ncs associatedReset ""
set_interface_property ncs ENABLED true
set_interface_property ncs EXPORT_OF ""
set_interface_property ncs PORT_NAME_MAP ""
set_interface_property ncs CMSIS_SVD_VARIABLES ""
set_interface_property ncs SVD_ADDRESS_GROUP ""

add_interface_port ncs ncs conduit_ncs Output CS_WIDTH

