# TCL File Generated by Component Editor 14.0
# Wed Dec 03 14:18:54 CST 2014
# DO NOT MODIFY


# 
# Bytes_to_LVDS "Bytes to LVDS" v1.0
#  2014.12.03.14:18:54
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module Bytes_to_LVDS
# 
set_module_property DESCRIPTION ""
set_module_property NAME Bytes_to_LVDS
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Bytes to LVDS"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK elaborate


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL bytes_to_lvds
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bytes_to_lvds.sv SYSTEM_VERILOG PATH bytes_to_lvds.sv TOP_LEVEL_FILE
add_fileset_file lvds_rx_x2_m10_0002.v VERILOG PATH lvds_rx_x2_m10/lvds_rx_x2_m10_0002.v
add_fileset_file lvds_rx_x2_m10.v VERILOG PATH lvds_rx_x2_m10.v
add_fileset_file lvds_rx_x2_c5.v VERILOG PATH lvds_rx_x2_c5.v
add_fileset_file lvds_tx_x2_m10_0002.v VERILOG PATH lvds_tx_x2_m10/lvds_tx_x2_m10_0002.v
add_fileset_file lvds_tx_x2_m10.v VERILOG PATH lvds_tx_x2_m10.v
add_fileset_file lvds_tx_x2_c5.v VERILOG PATH lvds_tx_x2_c5.v
add_fileset_file ddout_x1.v VERILOG PATH ddout_x1.v
add_fileset_file avst_fifo.v VERILOG PATH avst_fifo.v
add_fileset_file avst_phasecompfifo.v VERILOG PATH avst_phasecompfifo.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL bytes_to_lvds
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bytes_to_lvds.sv SYSTEM_VERILOG PATH bytes_to_lvds.sv
add_fileset_file lvds_rx_x2_m10_0002.v VERILOG PATH lvds_rx_x2_m10/lvds_rx_x2_m10_0002.v
add_fileset_file lvds_rx_x2_m10.v VERILOG PATH lvds_rx_x2_m10.v
add_fileset_file lvds_rx_x2_c5.v VERILOG PATH lvds_rx_x2_c5.v
add_fileset_file lvds_tx_x2_m10_0002.v VERILOG PATH lvds_tx_x2_m10/lvds_tx_x2_m10_0002.v
add_fileset_file lvds_tx_x2_m10.v VERILOG PATH lvds_tx_x2_m10.v
add_fileset_file lvds_tx_x2_c5.v VERILOG PATH lvds_tx_x2_c5.v
add_fileset_file ddout_x1.v VERILOG PATH ddout_x1.v
add_fileset_file avst_fifo.v VERILOG PATH avst_fifo.v
add_fileset_file avst_phasecompfifo.v VERILOG PATH avst_phasecompfifo.v

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL bytes_to_lvds
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bytes_to_lvds.sv SYSTEM_VERILOG PATH bytes_to_lvds.sv
add_fileset_file lvds_rx_x2_m10_0002.v VERILOG PATH lvds_rx_x2_m10/lvds_rx_x2_m10_0002.v
add_fileset_file lvds_rx_x2_m10.v VERILOG PATH lvds_rx_x2_m10.v
add_fileset_file lvds_rx_x2_c5.v VERILOG PATH lvds_rx_x2_c5.v
add_fileset_file lvds_tx_x2_m10_0002.v VERILOG PATH lvds_tx_x2_m10/lvds_tx_x2_m10_0002.v
add_fileset_file lvds_tx_x2_m10.v VERILOG PATH lvds_tx_x2_m10.v
add_fileset_file lvds_tx_x2_c5.v VERILOG PATH lvds_tx_x2_c5.v
add_fileset_file ddout_x1.v VERILOG PATH ddout_x1.v
add_fileset_file avst_fifo.v VERILOG PATH avst_fifo.v
add_fileset_file avst_phasecompfifo.v VERILOG PATH avst_phasecompfifo.v


# 
# parameters
# 
add_parameter PT_SLAVE BOOLEAN true
set_parameter_property PT_SLAVE DISPLAY_NAME "Contained within the slave interface?"
set_parameter_property PT_SLAVE DESCRIPTION "Check this box if this component is instantiated within the slave interface.  This option controls how the handshaking is performed between the master and slave bit aligner blocks."
add_parameter P_SLAVE STD_LOGIC_VECTOR 0
set_parameter_property P_SLAVE WIDTH 1
set_parameter_property P_SLAVE ALLOWED_RANGES 0:1
set_parameter_property P_SLAVE HDL_PARAMETER true
set_parameter_property P_SLAVE VISIBLE false
add_parameter PT_PCFIFO BOOLEAN true
set_parameter_property PT_PCFIFO DISPLAY_NAME "Include Phase Compensation FIFO for TX output"
set_parameter_property PT_PCFIFO DESCRIPTION "Adds phase compensation FIFO in TX LVDS block (default).  This is highly recommended when the RX and TX reference clocks are different, and will result in an additional 3 clock cycles of latency."
add_parameter P_PCFIFO STD_LOGIC_VECTOR 0
set_parameter_property P_PCFIFO WIDTH 1
set_parameter_property P_PCFIFO ALLOWED_RANGES 0:1
set_parameter_property P_PCFIFO DERIVED true
set_parameter_property P_PCFIFO HDL_PARAMETER true
set_parameter_property P_PCFIFO VISIBLE false
add_parameter P_OOSCNTR POSITIVE 32
set_parameter_property P_OOSCNTR DEFAULT_VALUE 8
set_parameter_property P_OOSCNTR DISPLAY_NAME OOS_Check_Interval
set_parameter_property P_OOSCNTR WIDTH ""
set_parameter_property P_OOSCNTR TYPE POSITIVE
set_parameter_property P_OOSCNTR UNITS bits
set_parameter_property P_OOSCNTR ALLOWED_RANGES {1:32}
set_parameter_property P_OOSCNTR DESCRIPTION "Interval for declaring OOS.  Aligner needs to see 2^n cycles of OOS data before declaring OOS."
set_parameter_property P_OOSCNTR HDL_PARAMETER true
add_parameter P_ALIGNSEQ0 STD_LOGIC_VECTOR 10 ""
set_parameter_property P_ALIGNSEQ0 DEFAULT_VALUE 10
set_parameter_property P_ALIGNSEQ0 DISPLAY_NAME Alignment_Sequence(0)
set_parameter_property P_ALIGNSEQ0 WIDTH 10
set_parameter_property P_ALIGNSEQ0 TYPE STD_LOGIC_VECTOR
set_parameter_property P_ALIGNSEQ0 UNITS None
set_parameter_property P_ALIGNSEQ0 DESCRIPTION "0/1/0 sequence used to provide pulses to the manual bitslip for the RX deserializer for default initial alignment"
set_parameter_property P_ALIGNSEQ0 HDL_PARAMETER true
add_parameter P_ALIGNSEQ1 STD_LOGIC_VECTOR 10 ""
set_parameter_property P_ALIGNSEQ1 DEFAULT_VALUE 10
set_parameter_property P_ALIGNSEQ1 DISPLAY_NAME Alignment_Sequence(1)
set_parameter_property P_ALIGNSEQ1 WIDTH 10
set_parameter_property P_ALIGNSEQ1 TYPE STD_LOGIC_VECTOR
set_parameter_property P_ALIGNSEQ1 UNITS None
set_parameter_property P_ALIGNSEQ1 DESCRIPTION "0/1/0 sequence used to provide pulses to the manual bitslip for the RX deserializer for default initial alignment"
set_parameter_property P_ALIGNSEQ1 HDL_PARAMETER true
add_parameter P_DEV_FAMILY STRING 0 ""
set_parameter_property P_DEV_FAMILY DEFAULT_VALUE 0
set_parameter_property P_DEV_FAMILY DISPLAY_NAME Device_Family
set_parameter_property P_DEV_FAMILY ALLOWED_RANGES {0:"Max\ 10" 1:"Cyclone\ V"}
set_parameter_property P_DEV_FAMILY WIDTH ""
set_parameter_property P_DEV_FAMILY TYPE STRING
set_parameter_property P_DEV_FAMILY UNITS None
set_parameter_property P_DEV_FAMILY DESCRIPTION ""
set_parameter_property P_DEV_FAMILY HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clkout_rx
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point aligner_ctrl
# 
add_interface aligner_ctrl conduit end
set_interface_property aligner_ctrl associatedClock ""
set_interface_property aligner_ctrl associatedReset ""
set_interface_property aligner_ctrl ENABLED true
set_interface_property aligner_ctrl EXPORT_OF ""
set_interface_property aligner_ctrl PORT_NAME_MAP ""
set_interface_property aligner_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property aligner_ctrl SVD_ADDRESS_GROUP ""

add_interface_port aligner_ctrl aligner_ena aligner_ena Input 1
add_interface_port aligner_ctrl aligner_shift aligner_shift Input 1
add_interface_port aligner_ctrl aligner_oos aligner_oos Output 1


# 
# connection point misc_status
# 
add_interface misc_status conduit end
set_interface_property misc_status associatedClock ""
set_interface_property misc_status associatedReset ""
set_interface_property misc_status ENABLED true
set_interface_property misc_status EXPORT_OF ""
set_interface_property misc_status PORT_NAME_MAP ""
set_interface_property misc_status CMSIS_SVD_VARIABLES ""
set_interface_property misc_status SVD_ADDRESS_GROUP ""

add_interface_port misc_status lvdspll_locked pll_locked Output 1


# 
# connection point out_bytes_stream
# 
add_interface out_bytes_stream avalon_streaming start
set_interface_property out_bytes_stream associatedClock clkout_rx
set_interface_property out_bytes_stream dataBitsPerSymbol 8
set_interface_property out_bytes_stream errorDescriptor ""
set_interface_property out_bytes_stream firstSymbolInHighOrderBits true
set_interface_property out_bytes_stream maxChannel 0
set_interface_property out_bytes_stream readyLatency 0
set_interface_property out_bytes_stream ENABLED true
set_interface_property out_bytes_stream EXPORT_OF ""
set_interface_property out_bytes_stream PORT_NAME_MAP ""
set_interface_property out_bytes_stream CMSIS_SVD_VARIABLES ""
set_interface_property out_bytes_stream SVD_ADDRESS_GROUP ""

add_interface_port out_bytes_stream avst_rxdata data Output 8
add_interface_port out_bytes_stream avst_rxready ready Input 1
add_interface_port out_bytes_stream avst_rxvalid valid Output 1


# 
# connection point in_bytes_stream
# 
add_interface in_bytes_stream avalon_streaming end
set_interface_property in_bytes_stream associatedClock clkout_rx
set_interface_property in_bytes_stream dataBitsPerSymbol 8
set_interface_property in_bytes_stream errorDescriptor ""
set_interface_property in_bytes_stream firstSymbolInHighOrderBits true
set_interface_property in_bytes_stream maxChannel 0
set_interface_property in_bytes_stream readyLatency 0
set_interface_property in_bytes_stream ENABLED true
set_interface_property in_bytes_stream EXPORT_OF ""
set_interface_property in_bytes_stream PORT_NAME_MAP ""
set_interface_property in_bytes_stream CMSIS_SVD_VARIABLES ""
set_interface_property in_bytes_stream SVD_ADDRESS_GROUP ""

add_interface_port in_bytes_stream avst_txdata data Input 8
add_interface_port in_bytes_stream avst_txready ready Output 1
add_interface_port in_bytes_stream avst_txvalid valid Input 1


# 
# connection point lvds_rx
# 
add_interface lvds_rx conduit end
set_interface_property lvds_rx associatedClock ""
set_interface_property lvds_rx associatedReset ""
set_interface_property lvds_rx ENABLED true
set_interface_property lvds_rx EXPORT_OF ""
set_interface_property lvds_rx PORT_NAME_MAP ""
set_interface_property lvds_rx CMSIS_SVD_VARIABLES ""
set_interface_property lvds_rx SVD_ADDRESS_GROUP ""

add_interface_port lvds_rx lvds_rxdata lvds Input 2


# 
# connection point lvds_tx
# 
add_interface lvds_tx conduit end
set_interface_property lvds_tx associatedClock ""
set_interface_property lvds_tx associatedReset ""
set_interface_property lvds_tx ENABLED true
set_interface_property lvds_tx EXPORT_OF ""
set_interface_property lvds_tx PORT_NAME_MAP ""
set_interface_property lvds_tx CMSIS_SVD_VARIABLES ""
set_interface_property lvds_tx SVD_ADDRESS_GROUP ""

add_interface_port lvds_tx lvds_txdata lvds Output 2


# 
# connection point clkout_rx
# 
add_interface clkout_rx clock start
set_interface_property clkout_rx associatedDirectClock ""
set_interface_property clkout_rx clockRate 0
set_interface_property clkout_rx clockRateKnown false
set_interface_property clkout_rx ENABLED true
set_interface_property clkout_rx EXPORT_OF ""
set_interface_property clkout_rx PORT_NAME_MAP ""
set_interface_property clkout_rx CMSIS_SVD_VARIABLES ""
set_interface_property clkout_rx SVD_ADDRESS_GROUP ""

add_interface_port clkout_rx rx_outclock clk Output 1


# 
# connection point clkout_tx
# 
add_interface clkout_tx clock start
set_interface_property clkout_tx associatedDirectClock ""
set_interface_property clkout_tx clockRate 0
set_interface_property clkout_tx clockRateKnown false
set_interface_property clkout_tx ENABLED true
set_interface_property clkout_tx EXPORT_OF ""
set_interface_property clkout_tx PORT_NAME_MAP ""
set_interface_property clkout_tx CMSIS_SVD_VARIABLES ""
set_interface_property clkout_tx SVD_ADDRESS_GROUP ""

add_interface_port clkout_tx tx_outclock clk Output 1


# 
# connection point clk_rxpll
# 
add_interface clk_rxpll clock end
set_interface_property clk_rxpll clockRate 0
set_interface_property clk_rxpll ENABLED true
set_interface_property clk_rxpll EXPORT_OF ""
set_interface_property clk_rxpll PORT_NAME_MAP ""
set_interface_property clk_rxpll CMSIS_SVD_VARIABLES ""
set_interface_property clk_rxpll SVD_ADDRESS_GROUP ""

add_interface_port clk_rxpll rxpll_refclk clk Input 1


# 
# connection point clk_txpll
# 
add_interface clk_txpll clock end
set_interface_property clk_txpll clockRate 0
set_interface_property clk_txpll ENABLED true
set_interface_property clk_txpll EXPORT_OF ""
set_interface_property clk_txpll PORT_NAME_MAP ""
set_interface_property clk_txpll CMSIS_SVD_VARIABLES ""
set_interface_property clk_txpll SVD_ADDRESS_GROUP ""

add_interface_port clk_txpll txpll_refclk clk Input 1

proc elaborate {} {
# Override the device family for this module, in case the system is being generated as the
#   two-device testbench.  This is to ensure that the proper simulation libraries are called
#   in.  It does not affect synthesis.
if {[ get_parameter_value P_DEV_FAMILY ] == "1" } {
  set_module_assignment "postgeneration.test.device_family" "cyclonev"
} else {
  set_module_assignment "postgeneration.test.device_family" "max10"
}

if {[ get_parameter_value PT_PCFIFO ] } {
  set_parameter_value P_PCFIFO 1
} else {
  set_parameter_value P_PCFIFO 0
}

if {[ get_parameter_value PT_PCFIFO ] } {
  set_parameter_value P_PCFIFO 1
} else {
  set_parameter_value P_PCFIFO 0
}

}

