# TCL File Generated by Component Editor 11.1sp2
# Wed May 09 11:12:33 BST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | export_clk_reset "export_clk_reset" v1.0
# | null 2012.05.09.11:12:33
# | 
# | 
# | D:/P4_workspaces/RFF_cj/depot/ssg/RF_Card/JESD204B/jesd204b_refdesign/ip/export_clk_reset.v
# | 
# |    ./export_clk_reset.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module export_clk_reset
# | 
set_module_property NAME export_clk_reset
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME export_clk_reset
set_module_property TOP_LEVEL_HDL_FILE export_clk_reset.v
set_module_property TOP_LEVEL_HDL_MODULE export_clk_reset
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME export_clk_reset
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file export_clk_reset.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tx_clk
# | 
add_interface tx_clk clock end
set_interface_property tx_clk clockRate 0

set_interface_property tx_clk ENABLED true

add_interface_port tx_clk tx_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tx_rstn
# | 
add_interface tx_rstn reset end
set_interface_property tx_rstn associatedClock tx_clk
set_interface_property tx_rstn synchronousEdges DEASSERT

set_interface_property tx_rstn ENABLED true

add_interface_port tx_rstn tx_rstn reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point rx_clk
# | 
add_interface rx_clk clock end
set_interface_property rx_clk clockRate 0

set_interface_property rx_clk ENABLED true

add_interface_port rx_clk rx_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point rx_rstn
# | 
add_interface rx_rstn reset end
set_interface_property rx_rstn associatedClock rx_clk
set_interface_property rx_rstn synchronousEdges DEASSERT

set_interface_property rx_rstn ENABLED true

add_interface_port rx_rstn rx_rstn reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point jesd_frm_clk_rst
# | 
add_interface jesd_frm_clk_rst conduit end

set_interface_property jesd_frm_clk_rst ENABLED true

add_interface_port jesd_frm_clk_rst expt_tx_clk export Output 1
add_interface_port jesd_frm_clk_rst expt_tx_rstn export Output 1
add_interface_port jesd_frm_clk_rst expt_rx_clk export Output 1
add_interface_port jesd_frm_clk_rst expt_rx_rstn export Output 1
add_interface_port jesd_frm_clk_rst expt_reconfig_clk export Output 1
add_interface_port jesd_frm_clk_rst expt_reconfig_rst export Output 1
add_interface_port jesd_frm_clk_rst expt_clkout export Output 1
add_interface_port jesd_frm_clk_rst expt_clkout_rstn export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reconfig_clk
# | 
add_interface reconfig_clk clock end
set_interface_property reconfig_clk clockRate 0

set_interface_property reconfig_clk ENABLED true

add_interface_port reconfig_clk reconfig_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reconfig_rst
# | 
add_interface reconfig_rst reset end
set_interface_property reconfig_rst associatedClock reconfig_clk
set_interface_property reconfig_rst synchronousEdges DEASSERT

set_interface_property reconfig_rst ENABLED true

add_interface_port reconfig_rst reconfig_rst reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clkout
# | 
add_interface clkout clock end
set_interface_property clkout clockRate 0

set_interface_property clkout ENABLED true

add_interface_port clkout clkout clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clkout_rstn
# | 
add_interface clkout_rstn reset end
set_interface_property clkout_rstn associatedClock clkout
set_interface_property clkout_rstn synchronousEdges DEASSERT

set_interface_property clkout_rstn ENABLED true

add_interface_port clkout_rstn clkout_rstn reset_n Input 1
# | 
# +-----------------------------------
