# TCL File Generated by Component Editor 8.0sp1
# Sat Sep 27 18:12:59 MDT 2008
# DO NOT MODIFY


# +-----------------------------------
# | 
# | my_jtag_mster "my_jtag_mster" v1.0
# | null 2008.09.27.18:12:59
# | 
# | 
# | ip/my_jtag_mster.v
# | 
# |    ./my_jtag_mster.v syn, sim
# |   
# | 
# +-----------------------------------


# +-----------------------------------
# | module my_jtag_mster
# | 
set_module_property NAME Avalon_Fast_Downloader
set_module_property VERSION 1.0
set_module_property GROUP "Bridges and Adapters/Memory Mapped"
set_module_property DISPLAY_NAME Avalon_Fast_Downloader
set_module_property TOP_LEVEL_HDL_FILE Avalon_Fast_Downloader.v
set_module_property TOP_LEVEL_HDL_MODULE Avalon_Fast_Downloader
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file Avalon_Fast_Downloader.v {SYNTHESIS SIMULATION}
#add_file jtag_phy.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point m1
# | 
add_interface m1 avalon start
set_interface_property m1 linewrapBursts false
set_interface_property m1 adaptsTo ""
set_interface_property m1 doStreamReads false
set_interface_property m1 doStreamWrites false
set_interface_property m1 burstOnBurstBoundariesOnly false

set_interface_property m1 ASSOCIATED_CLOCK clock_reset

add_interface_port m1 avm_m1_address address Output 32
add_interface_port m1 avm_m1_read read Output 1
add_interface_port m1 avm_m1_write write Output 1
add_interface_port m1 avm_m1_writedata writedata Output 8
add_interface_port m1 avm_m1_readdata readdata Input 8
add_interface_port m1 avm_m1_waitrequest waitrequest Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset ptfSchematicName ""

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset_n reset_n Input 1
# | 
# +-----------------------------------
