# TCL File Generated by Component Editor 13.0sp1
# Thu Feb 06 13:51:19 PST 2014
# DO NOT MODIFY


# 
# arriav_v_standalone_gigabit_xcvr "arriav_v_standalone_gigabit_xcvr" v1.0
#  2014.02.06.13:51:19
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module arriav_v_standalone_gigabit_xcvr
# 
set_module_property DESCRIPTION ""
set_module_property NAME arriav_v_standalone_gigabit_xcvr
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME arriav_v_standalone_gigabit_xcvr
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL arriav_eth_quartus_13
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file arriav_eth_quartus_13.v VERILOG PATH arriav_eth_quartus_13.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point phy_mgmt
# 
add_interface phy_mgmt avalon end
set_interface_property phy_mgmt addressUnits WORDS
set_interface_property phy_mgmt associatedClock clock_sink
set_interface_property phy_mgmt associatedReset reset_sink
set_interface_property phy_mgmt bitsPerSymbol 8
set_interface_property phy_mgmt burstOnBurstBoundariesOnly false
set_interface_property phy_mgmt burstcountUnits WORDS
set_interface_property phy_mgmt explicitAddressSpan 0
set_interface_property phy_mgmt holdTime 0
set_interface_property phy_mgmt linewrapBursts false
set_interface_property phy_mgmt maximumPendingReadTransactions 0
set_interface_property phy_mgmt readLatency 0
set_interface_property phy_mgmt readWaitTime 1
set_interface_property phy_mgmt setupTime 0
set_interface_property phy_mgmt timingUnits Cycles
set_interface_property phy_mgmt writeWaitTime 0
set_interface_property phy_mgmt ENABLED true
set_interface_property phy_mgmt EXPORT_OF ""
set_interface_property phy_mgmt PORT_NAME_MAP ""
set_interface_property phy_mgmt SVD_ADDRESS_GROUP ""

add_interface_port phy_mgmt phy_mgmt_read read Input 1
add_interface_port phy_mgmt phy_mgmt_readdata readdata Output 32
add_interface_port phy_mgmt phy_mgmt_waitrequest waitrequest Output 1
add_interface_port phy_mgmt phy_mgmt_write write Input 1
add_interface_port phy_mgmt phy_mgmt_writedata writedata Input 32
add_interface_port phy_mgmt phy_mgmt_address address Input 9
set_interface_assignment phy_mgmt embeddedsw.configuration.isFlash 0
set_interface_assignment phy_mgmt embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment phy_mgmt embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment phy_mgmt embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink phy_mgmt_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink phy_mgmt_clk_reset reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end tx_ready export Output 1
add_interface_port conduit_end rx_ready export Output 1
add_interface_port conduit_end pll_ref_clk export Input 1
add_interface_port conduit_end tx_serial_data export Output 1
add_interface_port conduit_end tx_forceelecidle export Input 1
add_interface_port conduit_end pll_locked export Output 1
add_interface_port conduit_end rx_serial_data export Input 1
add_interface_port conduit_end rx_is_lockedtoref export Output 1
add_interface_port conduit_end rx_is_lockedtodata export Output 1
add_interface_port conduit_end rx_signaldetect export Output 1
add_interface_port conduit_end tx_clkout export Output 1
add_interface_port conduit_end rx_clkout export Output 1
add_interface_port conduit_end tx_parallel_data export Input 10
add_interface_port conduit_end rx_parallel_data export Output 10
add_interface_port conduit_end reconfig_from_xcvr export Output 92
add_interface_port conduit_end reconfig_to_xcvr export Input 140

