# TCL File Generated by Component Editor 14.1
# Wed Apr 27 15:36:28 PDT 2016
# DO NOT MODIFY


# 
# av_sfp_xcvr_w_reconfig "av_sfp_xcvr_w_reconfig" v1.0
#  2016.04.27.15:36:28
# 
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 13.0


# 
# module av_sfp_xcvr_w_reconfig
# 
set_module_property DESCRIPTION ""
set_module_property NAME av_sfp_xcvr_w_reconfig
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME av_sfp_xcvr_w_reconfig
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL av_sfp
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file av_sfp.sv SYSTEM_VERILOG PATH av_sfp.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_125_mhz_for_control
set_interface_property avalon_slave associatedReset reset_for_125_mhz_control
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 1
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avalon_slave_waitrequest waitrequest Output 1
add_interface_port avalon_slave avalon_slave_readdata readdata Output 32
add_interface_port avalon_slave avalon_slave_readdatavalid readdatavalid Output 1
add_interface_port avalon_slave avalon_slave_burstcount burstcount Input 1
add_interface_port avalon_slave avalon_slave_writedata writedata Input 32
add_interface_port avalon_slave avalon_slave_address address Input 16
add_interface_port avalon_slave avalon_slave_write write Input 1
add_interface_port avalon_slave avalon_slave_read read Input 1
add_interface_port avalon_slave avalon_slave_byteenable byteenable Input 4
add_interface_port avalon_slave avalon_slave_debugaccess debugaccess Input 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0
# set_parameter_property system SYSTEM_INFO {ADDRESS_MAP "<address-map> <slave name='xcvr' start='0x0' end='0x800' /> <slave name='xcvr_reconfig' start='0x800' end='0xA00' /> </address-map>"}

# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end ethernet_tx_ready export Output 1
add_interface_port conduit_end ethernet_rx_ready export Output 1
add_interface_port conduit_end xcvr_clk_pll_locked export Output 1
add_interface_port conduit_end SFP_TX export Output 1
add_interface_port conduit_end SFP_RX export Input 1
add_interface_port conduit_end tbi_tx_clkout export Output 1
add_interface_port conduit_end tbi_rx_clkout export Output 1
add_interface_port conduit_end tbi_tx_d export Input 10
add_interface_port conduit_end tbi_rx_d export Output 10
add_interface_port conduit_end rx_is_lockedtoref export Output 1
add_interface_port conduit_end rx_is_lockedtodata export Output 1
add_interface_port conduit_end rx_signaldetect export Output 1
add_interface_port conduit_end tx_forceelecidle export Input 1
add_interface_port conduit_end busy export Output 1
add_interface_port conduit_end tx_cal_busy export Output 1
add_interface_port conduit_end rx_cal_busy export Output 1


# 
# connection point clock_125_mhz_for_control
# 
add_interface clock_125_mhz_for_control clock end
set_interface_property clock_125_mhz_for_control clockRate 0
set_interface_property clock_125_mhz_for_control ENABLED true
set_interface_property clock_125_mhz_for_control EXPORT_OF ""
set_interface_property clock_125_mhz_for_control PORT_NAME_MAP ""
set_interface_property clock_125_mhz_for_control CMSIS_SVD_VARIABLES ""
set_interface_property clock_125_mhz_for_control SVD_ADDRESS_GROUP ""

add_interface_port clock_125_mhz_for_control ethernet_clk_125mhz_control_clk clk Input 1


# 
# connection point reset_for_125_mhz_control
# 
add_interface reset_for_125_mhz_control reset end
set_interface_property reset_for_125_mhz_control associatedClock clock_125_mhz_for_control
set_interface_property reset_for_125_mhz_control synchronousEdges NONE
set_interface_property reset_for_125_mhz_control ENABLED true
set_interface_property reset_for_125_mhz_control EXPORT_OF ""
set_interface_property reset_for_125_mhz_control PORT_NAME_MAP ""
set_interface_property reset_for_125_mhz_control CMSIS_SVD_VARIABLES ""
set_interface_property reset_for_125_mhz_control SVD_ADDRESS_GROUP ""

add_interface_port reset_for_125_mhz_control ethernet_clk_125mhz_reset_n reset_n Input 1


# 
# connection point clock_125_mhz_for_sfp_pll
# 
add_interface clock_125_mhz_for_sfp_pll clock end
set_interface_property clock_125_mhz_for_sfp_pll clockRate 0
set_interface_property clock_125_mhz_for_sfp_pll ENABLED true
set_interface_property clock_125_mhz_for_sfp_pll EXPORT_OF ""
set_interface_property clock_125_mhz_for_sfp_pll PORT_NAME_MAP ""
set_interface_property clock_125_mhz_for_sfp_pll CMSIS_SVD_VARIABLES ""
set_interface_property clock_125_mhz_for_sfp_pll SVD_ADDRESS_GROUP ""

add_interface_port clock_125_mhz_for_sfp_pll ethernet_125Mhz_pll_base_clk clk Input 1

