# TCL File Generated by Component Editor 14.0
# Tue Nov 25 21:04:57 CST 2014
# DO NOT MODIFY


# 
# avalon_slave_to_packets "Avalon Transaction to Packets" v1.0
#  2014.11.25.21:04:57
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module avalon_slave_to_packets
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_slave_to_packets
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon Transaction to Packets"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK elaborate


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avs_to_packets_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avs_to_packets_if.sv SYSTEM_VERILOG PATH avs_to_packets_if.sv
add_fileset_file avs_to_packets.sv SYSTEM_VERILOG PATH avs_to_packets.sv
add_fileset_file avs_to_packets_wrapper.sv SYSTEM_VERILOG PATH avs_to_packets_wrapper.sv TOP_LEVEL_FILE
add_fileset_file avmm_transaction_fifo.v VERILOG PATH avmm_transaction_fifo.v
add_fileset_file avmm_cmdresp_fifo.v VERILOG PATH avmm_cmdresp_fifo.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avs_to_packets_wrapper
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avs_to_packets_if.sv SYSTEM_VERILOG PATH avs_to_packets_if.sv
add_fileset_file avs_to_packets.sv SYSTEM_VERILOG PATH avs_to_packets.sv
add_fileset_file avs_to_packets_wrapper.sv SYSTEM_VERILOG PATH avs_to_packets_wrapper.sv TOP_LEVEL_FILE
add_fileset_file avmm_transaction_fifo.v VERILOG PATH avmm_transaction_fifo.v
add_fileset_file avmm_cmdresp_fifo.v VERILOG PATH avmm_cmdresp_fifo.v

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL avs_to_packets_wrapper
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avs_to_packets_if.sv SYSTEM_VERILOG PATH avs_to_packets_if.sv
add_fileset_file avs_to_packets.sv SYSTEM_VERILOG PATH avs_to_packets.sv
add_fileset_file avs_to_packets_wrapper.sv SYSTEM_VERILOG PATH avs_to_packets_wrapper.sv TOP_LEVEL_FILE
add_fileset_file avmm_transaction_fifo.v VERILOG PATH avmm_transaction_fifo.v
add_fileset_file avmm_cmdresp_fifo.v VERILOG PATH avmm_cmdresp_fifo.v


# 
# parameters
# 
add_parameter P_AWIDTH POSITIVE 32
set_parameter_property P_AWIDTH DEFAULT_VALUE 24
set_parameter_property P_AWIDTH DISPLAY_NAME "Address Width"
set_parameter_property P_AWIDTH ALLOWED_RANGES {1:32}
set_parameter_property P_AWIDTH WIDTH ""
set_parameter_property P_AWIDTH TYPE POSITIVE
set_parameter_property P_AWIDTH UNITS bits
set_parameter_property P_AWIDTH DESCRIPTION "Number of address bits required."
set_parameter_property P_AWIDTH HDL_PARAMETER true

add_parameter P_MAXBURSTSTRING STRING 32
set_parameter_property P_MAXBURSTSTRING DEFAULT_VALUE 1
set_parameter_property P_MAXBURSTSTRING DISPLAY_NAME "Maximum Burst Width"
set_parameter_property P_MAXBURSTSTRING ALLOWED_RANGES {1 2 3 4 5 6}
set_parameter_property P_MAXBURSTSTRING WIDTH ""
set_parameter_property P_MAXBURSTSTRING TYPE STRING
set_parameter_property P_MAXBURSTSTRING UNITS None
set_parameter_property P_MAXBURSTSTRING DESCRIPTION "Maximum size for burst transactions.  If set to '1', bursting is disabled.  The valid choices for bursting are 1, 4, 8, 16, or 32."
set_parameter_property P_MAXBURSTSTRING HDL_PARAMETER false

add_parameter P_MAXBURSTSIZE INTEGER 32
set_parameter_property P_MAXBURSTSIZE DISPLAY_NAME "Maximum Burst Size"
set_parameter_property P_MAXBURSTSIZE DERIVED true
set_parameter_property P_MAXBURSTSIZE HDL_PARAMETER false

add_parameter P_MAXBURSTWIDTH INTEGER 32
set_parameter_property P_MAXBURSTWIDTH DERIVED true
set_parameter_property P_MAXBURSTWIDTH HDL_PARAMETER true
set_parameter_property P_MAXBURSTWIDTH VISIBLE false

add_parameter P_FIFOSIZELOGN INTEGER 32
set_parameter_property P_FIFOSIZELOGN DEFAULT_VALUE 2
set_parameter_property P_FIFOSIZELOGN ALLOWED_RANGES {2:5}
set_parameter_property P_FIFOSIZELOGN DERIVED true
set_parameter_property P_FIFOSIZELOGN HDL_PARAMETER true
set_parameter_property P_FIFOSIZELOGN VISIBLE false

# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avmm_slave
# 
add_interface avmm_slave avalon end
set_interface_property avmm_slave addressUnits WORDS
set_interface_property avmm_slave associatedClock clock
set_interface_property avmm_slave associatedReset reset
set_interface_property avmm_slave bitsPerSymbol 8
set_interface_property avmm_slave burstOnBurstBoundariesOnly false
set_interface_property avmm_slave burstcountUnits WORDS
set_interface_property avmm_slave explicitAddressSpan 0
set_interface_property avmm_slave holdTime 0
set_interface_property avmm_slave linewrapBursts false
#set_interface_property avmm_slave maximumPendingReadTransactions 1
set_interface_property avmm_slave maximumPendingWriteTransactions 0
set_interface_property avmm_slave readLatency 0
set_interface_property avmm_slave readWaitTime 1
set_interface_property avmm_slave setupTime 0
set_interface_property avmm_slave timingUnits Cycles
set_interface_property avmm_slave writeWaitTime 0
set_interface_property avmm_slave ENABLED true
set_interface_property avmm_slave EXPORT_OF ""
set_interface_property avmm_slave PORT_NAME_MAP ""
set_interface_property avmm_slave CMSIS_SVD_VARIABLES ""
set_interface_property avmm_slave SVD_ADDRESS_GROUP ""

add_interface_port avmm_slave avs_readdatavalid readdatavalid Output 1
add_interface_port avmm_slave avs_waitrequest waitrequest Output 1
add_interface_port avmm_slave avs_readdata readdata Output 8
add_interface_port avmm_slave avs_writedata writedata Input 8
add_interface_port avmm_slave avs_address address Input P_AWIDTH
add_interface_port avmm_slave avs_burstcount burstcount Input P_MAXBURSTWIDTH
add_interface_port avmm_slave avs_write write Input 1
add_interface_port avmm_slave avs_read read Input 1
set_interface_assignment avmm_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avmm_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avmm_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avmm_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avst_source
# 
add_interface avst_source avalon_streaming start
set_interface_property avst_source associatedClock clock
set_interface_property avst_source associatedReset reset
set_interface_property avst_source dataBitsPerSymbol 8
set_interface_property avst_source errorDescriptor ""
set_interface_property avst_source firstSymbolInHighOrderBits true
set_interface_property avst_source maxChannel 0
set_interface_property avst_source readyLatency 0
set_interface_property avst_source ENABLED true
set_interface_property avst_source EXPORT_OF ""
set_interface_property avst_source PORT_NAME_MAP ""
set_interface_property avst_source CMSIS_SVD_VARIABLES ""
set_interface_property avst_source SVD_ADDRESS_GROUP ""

add_interface_port avst_source avst_out_data data Output 8
add_interface_port avst_source avst_out_valid valid Output 1
add_interface_port avst_source avst_out_ready ready Input 1
add_interface_port avst_source avst_out_sop startofpacket Output 1
add_interface_port avst_source avst_out_eop endofpacket Output 1


# 
# connection point avst_sink
# 
add_interface avst_sink avalon_streaming end
set_interface_property avst_sink associatedClock clock
set_interface_property avst_sink associatedReset reset
set_interface_property avst_sink dataBitsPerSymbol 8
set_interface_property avst_sink errorDescriptor ""
set_interface_property avst_sink firstSymbolInHighOrderBits true
set_interface_property avst_sink maxChannel 0
set_interface_property avst_sink readyLatency 0
set_interface_property avst_sink ENABLED true
set_interface_property avst_sink EXPORT_OF ""
set_interface_property avst_sink PORT_NAME_MAP ""
set_interface_property avst_sink CMSIS_SVD_VARIABLES ""
set_interface_property avst_sink SVD_ADDRESS_GROUP ""

add_interface_port avst_sink avst_in_ready ready Output 1
add_interface_port avst_sink avst_in_data data Input 8
add_interface_port avst_sink avst_in_valid valid Input 1
add_interface_port avst_sink avst_in_sop startofpacket Input 1
add_interface_port avst_sink avst_in_eop endofpacket Input 1

proc elaborate {} {
# Optionally disable the burst capability
if {[ get_parameter_value P_MAXBURSTSTRING ] == "1" } {
  set_port_property avs_burstcount termination true
  set_port_property avs_burstcount termination_value 1
}
# Calculate the parameters to pass to the HDL wrappper
set_parameter_value P_MAXBURSTSIZE [expr 2 ** ( [get_parameter_value P_MAXBURSTSTRING] - 1 ) ]
set_parameter_value P_MAXBURSTWIDTH [get_parameter_value P_MAXBURSTSTRING]
# Set the FIFO depth according to burst size, but have a minimum depth
#    of 4 words
if {[ get_parameter_value P_MAXBURSTSTRING ] < 3 } {
  set_parameter_value P_FIFOSIZELOGN 2
} else {
  set_parameter_value P_FIFOSIZELOGN [expr [get_parameter_value P_MAXBURSTWIDTH] - 1]
}
# Set the max pending transactions for the slave AVMM interface,
#    according to the FIFO depth
set_interface_property avmm_slave maximumPendingReadTransactions [expr 2 ** [get_parameter_value P_FIFOSIZELOGN]]
}

