# TCL File Generated by Component Editor 13.0sp1
# Wed May 21 12:43:53 PDT 2014
# DO NOT MODIFY


# 
# sd_spi_master "sd_spi_master" v1.0
#  2014.05.21.12:43:53
# SD SPI Master Hardware Implementation
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module sd_spi_master
# 
set_module_property DESCRIPTION "SD SPI Master Hardware Implementation"
set_module_property NAME sd_spi_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sd_spi_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL spiMaster
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file spiMaster.v VERILOG PATH spiMaster.v
add_fileset_file spiMaster_defines.v VERILOG PATH spiMaster_defines.v
add_fileset_file spiMaster_timescale.v VERILOG PATH spiMaster_timescale.v
add_fileset_file ctrlStsRegBI.v VERILOG PATH ctrlStsRegBI.v
add_fileset_file initSD.v VERILOG PATH initSD.v
add_fileset_file readWriteSDBlock.v VERILOG PATH readWriteSDBlock.v
add_fileset_file readWriteSPIWireData.v VERILOG PATH readWriteSPIWireData.v
add_fileset_file sendCmd.v VERILOG PATH sendCmd.v
add_fileset_file sm_dpMem_dc.v VERILOG PATH sm_dpMem_dc.v
add_fileset_file sm_fifoRTL.v VERILOG PATH sm_fifoRTL.v
add_fileset_file sm_RxFifo.v VERILOG PATH sm_RxFifo.v
add_fileset_file sm_RxFifoBI.v VERILOG PATH sm_RxFifoBI.v
add_fileset_file sm_TxFifo.v VERILOG PATH sm_TxFifo.v
add_fileset_file sm_TxFifoBI.v VERILOG PATH sm_TxFifoBI.v
add_fileset_file spiCtrl.v VERILOG PATH spiCtrl.v
add_fileset_file spiMasterWishBoneBI.v VERILOG PATH spiMasterWishBoneBI.v
add_fileset_file spiTxRxData.v VERILOG PATH spiTxRxData.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 data_o readdata Output 8
add_interface_port avalon_slave_0 strobe_i chipselect Input 1
add_interface_port avalon_slave_0 we_i write Input 1
add_interface_port avalon_slave_0 address_i address Input 8
add_interface_port avalon_slave_0 data_i writedata Input 8
add_interface_port avalon_slave_0 ack_o waitrequest_n Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_i reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end spiClkOut export Output 1
add_interface_port conduit_end spiDataIn export Input 1
add_interface_port conduit_end spiDataOut export Output 1
add_interface_port conduit_end spiCS_n export Output 1
add_interface_port conduit_end spiSysClk export Input 1

