# TCL File Generated by Altera University Program
# DO NOT MODIFY

source "../../../lib/aup_version.tcl"
source "../../../lib/aup_ip_generator.tcl"

# +-----------------------------------
# | module frame_buffer_avalon_video_dma_controller
# | 
set_module_property DESCRIPTION "Ikomed Frame Buffer"
set_module_property NAME frame_buffer_avalon_video_dma_controller
set_module_property VERSION $aup_version
set_module_property GROUP "University Program/Audio & Video/Video"
set_module_property AUTHOR "Altera University Program"
set_module_property DISPLAY_NAME "DMA Controller"
set_module_property DATASHEET_URL "[pwd]/../doc/Video.pdf"
#set_module_property TOP_LEVEL_HDL_FILE frame_buffer_avalon_video_dma_controller.v
#set_module_property TOP_LEVEL_HDL_MODULE frame_buffer_avalon_video_dma_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property HIDE_FROM_QUARTUS true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property ELABORATION_CALLBACK elaborate
set_module_property GENERATION_CALLBACK generate
set_module_property HIDE_FROM_SOPC true
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
#add_file frame_buffer_avalon_video_dma_controller.v {SYNTHESIS SIMULATION}
add_file "hdl/frame_buffer_video_dma_control_slave.v" {SYNTHESIS SIMULATION}
add_file "hdl/frame_buffer_video_dma_to_stream.v" {SYNTHESIS SIMULATION}
add_file "hdl/frame_buf_burst_write_master.v" {SYNTHESIS SIMULATION}
add_file "hdl/frame_buf_burst_read_master.v" {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter mode string "From Stream to Memory" 
set_parameter_property mode DISPLAY_NAME "DMA Direction"
set_parameter_property mode GROUP "Mode"
set_parameter_property mode UNITS None
set_parameter_property mode AFFECTS_ELABORATION true
set_parameter_property mode AFFECTS_GENERATION true
set_parameter_property mode ALLOWED_RANGES {"From Stream to Memory" "From Memory to Stream"}
set_parameter_property mode VISIBLE true
set_parameter_property mode ENABLED true

add_parameter num_pixels_in_frame positive "320"
set_parameter_property num_pixels_in_frame DISPLAY_NAME "Num of Pixels In Frame"
set_parameter_property num_pixels_in_frame GROUP "Frame Resolution"
set_parameter_property num_pixels_in_frame UNITS None
set_parameter_property num_pixels_in_frame AFFECTS_ELABORATION true
set_parameter_property num_pixels_in_frame AFFECTS_GENERATION true
set_parameter_property num_pixels_in_frame VISIBLE true
set_parameter_property num_pixels_in_frame ENABLED true


add_parameter bits_per_pixel positive "8"
set_parameter_property bits_per_pixel DISPLAY_NAME "Num. Bits per Pixel"
set_parameter_property bits_per_pixel GROUP "Pixel Format"
set_parameter_property bits_per_pixel UNITS None
set_parameter_property bits_per_pixel AFFECTS_ELABORATION true
set_parameter_property bits_per_pixel AFFECTS_GENERATION true
set_parameter_property bits_per_pixel ALLOWED_RANGES {1:1024}
set_parameter_property bits_per_pixel VISIBLE true
set_parameter_property bits_per_pixel ENABLED true

add_parameter parallelization_ratio positive "3"
set_parameter_property parallelization_ratio DISPLAY_NAME "Num Pixels In Parallel To/From Memory"
set_parameter_property parallelization_ratio GROUP "Pixel Format"
set_parameter_property parallelization_ratio UNITS None
set_parameter_property parallelization_ratio AFFECTS_ELABORATION true
set_parameter_property parallelization_ratio AFFECTS_GENERATION true
set_parameter_property parallelization_ratio ALLOWED_RANGES {1 2 4 8 16 32 64 128 256 512 1024 2048 4096}
set_parameter_property parallelization_ratio VISIBLE true
set_parameter_property parallelization_ratio ENABLED true

add_parameter dma_enabled boolean true
set_parameter_property dma_enabled DISPLAY_NAME "Enabled DMA transfer on reset"
set_parameter_property dma_enabled GROUP "Control"
set_parameter_property dma_enabled UNITS None
set_parameter_property dma_enabled AFFECTS_ELABORATION true
set_parameter_property dma_enabled AFFECTS_GENERATION true
set_parameter_property dma_enabled VISIBLE true
set_parameter_property dma_enabled ENABLED true

add_parameter use_external_backbuffer boolean true
set_parameter_property use_external_backbuffer DISPLAY_NAME "Use External Backbuffer Address"
set_parameter_property use_external_backbuffer GROUP "Control"
set_parameter_property use_external_backbuffer UNITS None
set_parameter_property use_external_backbuffer AFFECTS_ELABORATION true
set_parameter_property use_external_backbuffer AFFECTS_GENERATION true
set_parameter_property use_external_backbuffer VISIBLE true
set_parameter_property use_external_backbuffer ENABLED true

add_parameter always_do_buffer_swap boolean true
set_parameter_property always_do_buffer_swap DISPLAY_NAME "Always Do Buffer Swap"
set_parameter_property always_do_buffer_swap GROUP "Control"
set_parameter_property always_do_buffer_swap UNITS None
set_parameter_property always_do_buffer_swap AFFECTS_ELABORATION true
set_parameter_property always_do_buffer_swap AFFECTS_GENERATION true
set_parameter_property always_do_buffer_swap VISIBLE true
set_parameter_property always_do_buffer_swap ENABLED true

add_parameter          override_external_swap_buffers_now         boolean false
set_parameter_property override_external_swap_buffers_now         DISPLAY_NAME "Use Avalon-MM for External Swap Bufs Now"
set_parameter_property override_external_swap_buffers_now         GROUP "Control"
set_parameter_property override_external_swap_buffers_now         UNITS None
set_parameter_property override_external_swap_buffers_now         AFFECTS_ELABORATION true
set_parameter_property override_external_swap_buffers_now         AFFECTS_GENERATION true
set_parameter_property override_external_swap_buffers_now         VISIBLE true
set_parameter_property override_external_swap_buffers_now         ENABLED true


add_parameter          override_val_for_external_swap_buffers_now boolean false
set_parameter_property override_val_for_external_swap_buffers_now DISPLAY_NAME "Override Val. for External Swap Bufs Now"
set_parameter_property override_val_for_external_swap_buffers_now GROUP "Control"
set_parameter_property override_val_for_external_swap_buffers_now UNITS None
set_parameter_property override_val_for_external_swap_buffers_now AFFECTS_ELABORATION true
set_parameter_property override_val_for_external_swap_buffers_now AFFECTS_GENERATION true
set_parameter_property override_val_for_external_swap_buffers_now VISIBLE true
set_parameter_property override_val_for_external_swap_buffers_now ENABLED true



add_parameter watchdog_enabled boolean true
set_parameter_property watchdog_enabled DISPLAY_NAME "Enable Watchdog"
set_parameter_property watchdog_enabled GROUP "Control"
set_parameter_property watchdog_enabled UNITS None
set_parameter_property watchdog_enabled AFFECTS_ELABORATION true
set_parameter_property watchdog_enabled AFFECTS_GENERATION true
set_parameter_property watchdog_enabled VISIBLE true
set_parameter_property watchdog_enabled ENABLED true

add_parameter          num_watchdog_bits positive "64"
set_parameter_property num_watchdog_bits DISPLAY_NAME "Num. Watchdog Bits"
set_parameter_property num_watchdog_bits GROUP "Control"
set_parameter_property num_watchdog_bits UNITS None
set_parameter_property num_watchdog_bits AFFECTS_ELABORATION true
set_parameter_property num_watchdog_bits AFFECTS_GENERATION true
set_parameter_property num_watchdog_bits ALLOWED_RANGES {1:64}
set_parameter_property num_watchdog_bits VISIBLE true
set_parameter_property num_watchdog_bits ENABLED true

add_parameter          address_width positive "32"
set_parameter_property address_width DISPLAY_NAME "Address Width"
set_parameter_property address_width GROUP "Control"
set_parameter_property address_width UNITS None
set_parameter_property address_width AFFECTS_ELABORATION true
set_parameter_property address_width AFFECTS_GENERATION true
set_parameter_property address_width ALLOWED_RANGES {1:32}
set_parameter_property address_width VISIBLE true
set_parameter_property address_width ENABLED true

add_parameter          watchdog_count string "2000000000"
set_parameter_property watchdog_count DISPLAY_NAME "Watchdog Count"
set_parameter_property watchdog_count DISPLAY_HINT decimal
set_parameter_property watchdog_count GROUP "Control"
set_parameter_property watchdog_count UNITS None
set_parameter_property watchdog_count AFFECTS_ELABORATION true
set_parameter_property watchdog_count AFFECTS_GENERATION true
set_parameter_property watchdog_count VISIBLE true
set_parameter_property watchdog_count ENABLED true


add_parameter swap_symbols_for_ddr_write boolean false
set_parameter_property swap_symbols_for_ddr_write DISPLAY_NAME "Swap Symbols Order for DMA"
set_parameter_property swap_symbols_for_ddr_write GROUP "Control"
set_parameter_property swap_symbols_for_ddr_write UNITS None
set_parameter_property swap_symbols_for_ddr_write AFFECTS_ELABORATION true
set_parameter_property swap_symbols_for_ddr_write AFFECTS_GENERATION true
set_parameter_property swap_symbols_for_ddr_write VISIBLE true
set_parameter_property swap_symbols_for_ddr_write ENABLED true

# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk enabled true

add_interface_port clk clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset enabled true
set_interface_property reset synchronousEdges DEASSERT

add_interface_port reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | Elaboration function
# | 

proc my_clog { base x } {
  return [expr {int(ceil(log($x)/log($base)))}]
}
proc compute_mdw { x } {
  return [expr {int(pow(2,[my_clog 2 [expr {(int(ceil(double($x)/8.0))*8)}]]))}]
}

proc elaborate {} {
	set mode				[ get_parameter_value "mode"]
	set num_pixels_in_frame [ get_parameter_value "num_pixels_in_frame" ]
	set bits_per_pixel			[ get_parameter_value "bits_per_pixel" ]
	set parallelization_ratio		[ get_parameter_value "parallelization_ratio" ]
	set num_of_dma_locations [expr {$num_pixels_in_frame/$parallelization_ratio}];

	set dw [expr $bits_per_pixel * $parallelization_ratio]
	set ew [expr {[my_clog 2 $parallelization_ratio]}]
	set mdw [compute_mdw $dw]
	# if { $dw <= 8 } {
	# 	set mdw 8
	# } elseif { $dw <= 16 } {
	# 	set mdw 16
	# } elseif { $dw <= 32 } {
	# 	set mdw 32
	# } else {
	# 	set mdw 64
	# }
	

	# 
	# connection point snoop_interface
	# 
	add_interface snoop_interface conduit end
	set_interface_property snoop_interface associatedReset reset
	set_interface_property snoop_interface ENABLED true

	add_interface_port snoop_interface snoop_master_readdata                export Output $mdw
	add_interface_port snoop_interface snoop_master_readdatavalid           export Output 1
	add_interface_port snoop_interface snoop_master_waitrequest             export Output 1
	add_interface_port snoop_interface snoop_master_address                 export Output 32
	add_interface_port snoop_interface snoop_master_write                   export Output 1
	add_interface_port snoop_interface snoop_master_writedata               export Output $mdw
	add_interface_port snoop_interface snoop_master_read                    export Output 1
	add_interface_port snoop_interface snoop_stream_data                    export Output $dw
	add_interface_port snoop_interface snoop_stream_startofpacket           export Output 1
	add_interface_port snoop_interface snoop_stream_endofpacket	            export Output 1
	add_interface_port snoop_interface snoop_stream_empty                   export Output $ew
	add_interface_port snoop_interface snoop_stream_valid                   export Output 1
	add_interface_port snoop_interface snoop_stream_ready                   export Output 1
	add_interface_port snoop_interface snoop_state                          export Output 16
	add_interface_port snoop_interface snoop_back_buf_start_address                         export Output 32
	add_interface_port snoop_interface snoop_dma_enabled                                    export Output 1
	add_interface_port snoop_interface snoop_soft_reset_now                                 export Output 1
	add_interface_port snoop_interface snoop_last_written_buf_start_address                 export Output 32
	add_interface_port snoop_interface snoop_external_priority_backbuffer_address           export Output 32
	add_interface_port snoop_interface snoop_use_external_priority_backbuffer               export Output 1
	add_interface_port snoop_interface snoop_currently_processing_packet                    export Output 1
	add_interface_port snoop_interface snoop_pause_after_each_frame                         export Output 1
	add_interface_port snoop_interface snoop_get_frame_now                                  export Output 1
	add_interface_port snoop_interface snoop_get_frame_now_ack                              export Output 1
	add_interface_port snoop_interface snoop_buffer_start_address                           export Output 32
    add_interface_port snoop_interface snoop_num_buffer_swaps                               export Output 32
	add_interface_port snoop_interface snoop_num_of_packets_processed                       export Output 32
	add_interface_port snoop_interface snoop_num_of_repeated_packets                        export Output 32
	add_interface_port snoop_interface snoop_num_of_packets_finished_processing             export Output 32
	add_interface_port snoop_interface snoop_write_bytes_left                               export Output 32
	add_interface_port snoop_interface snoop_swap_buffers_now                               export Output 1
	add_interface_port snoop_interface snoop_external_swap_buffer_now                       export Output 1
	add_interface_port snoop_interface snoop_wait_for_swap                                  export Output 1
	add_interface_port snoop_interface out_of_band_data_received                            export Output 1
	add_interface_port snoop_interface watchdog_counter                                     export Output 64
	add_interface_port snoop_interface watchdog_reset                                       export Output 1
	add_interface_port snoop_interface increase_watchdog_event_count                        export Output 1
	add_interface_port snoop_interface num_watchdog_events                                  export Output 32
	add_interface_port snoop_interface num_of_discarded_packets                             export Output 32
	add_interface_port snoop_interface discarded_packet_event                               export Output 1
		
	           
	add_interface hw_control conduit end
	set_interface_property hw_control associatedReset reset
	set_interface_property hw_control ENABLED true	
	add_interface_port hw_control state                                export Output 16
	add_interface_port hw_control buffer_start_address                 export Output 32
	add_interface_port hw_control back_buf_start_address               export Output 32      
	add_interface_port hw_control last_written_buf_start_address       export Output 32
	add_interface_port hw_control external_priority_backbuffer_address export Input  32
	add_interface_port hw_control use_external_priority_backbuffer     export Output 1
	add_interface_port hw_control dma_enabled                          export Output 1
	add_interface_port hw_control pause_after_each_frame               export Input 1
	add_interface_port hw_control currently_processing_packet          export Output 1
	add_interface_port hw_control get_frame_now                        export Input 1
	add_interface_port hw_control get_frame_now_ack                    export Output 1
	add_interface_port hw_control num_buffer_swaps                     export Output 32
	add_interface_port hw_control num_of_packets_processed             export Output 32
	add_interface_port hw_control num_of_repeated_packets              export Output 32
	add_interface_port hw_control swap_buffers_now                     export Output 1
	add_interface_port hw_control external_swap_buffer_now             export Input 1
	add_interface_port hw_control wait_for_swap                        export Output 1
	add_interface_port hw_control default_buffer_address               export input 32
	add_interface_port hw_control default_back_buf_address             export input 32
	
	if { $mode == "From Stream to Memory" } {
		# +-----------------------------------
		# | connection point avalon_dma_sink
		# | 
		add_interface avalon_dma_sink avalon_streaming end
		set_interface_property avalon_dma_sink associatedClock clk
		set_interface_property avalon_dma_sink associatedReset reset
		set_interface_property avalon_dma_sink dataBitsPerSymbol $bits_per_pixel
		set_interface_property avalon_dma_sink errorDescriptor ""
		set_interface_property avalon_dma_sink maxChannel 0
		set_interface_property avalon_dma_sink readyLatency 0
		set_interface_property avalon_dma_sink symbolsPerBeat $parallelization_ratio

		add_interface_port avalon_dma_sink stream_data data Input $dw
		add_interface_port avalon_dma_sink stream_startofpacket startofpacket Input 1
		add_interface_port avalon_dma_sink stream_endofpacket endofpacket Input 1
#		add_interface_port avalon_dma_sink stream_empty empty Input $ew
		add_interface_port avalon_dma_sink stream_valid valid Input 1
		add_interface_port avalon_dma_sink stream_ready ready Output 1
		# | 
		# +-----------------------------------
		
		# +-----------------------------------
		# | connection point avalon_dma_control_slave
		# | 
		add_interface avalon_dma_control_slave avalon end
		set_interface_property avalon_dma_control_slave addressAlignment DYNAMIC
		set_interface_property avalon_dma_control_slave associatedClock clk
		set_interface_property avalon_dma_control_slave associatedReset reset
		set_interface_property avalon_dma_control_slave bridgesToMaster ""
		set_interface_property avalon_dma_control_slave burstOnBurstBoundariesOnly false
		#set_interface_property avalon_dma_control_slave explicitAddressSpan 16
		set_interface_property avalon_dma_control_slave holdTime 0
		set_interface_property avalon_dma_control_slave isBigEndian  false
		set_interface_property avalon_dma_control_slave isFlash false
		set_interface_property avalon_dma_control_slave isMemoryDevice false
		set_interface_property avalon_dma_control_slave isNonVolatileStorage false
		set_interface_property avalon_dma_control_slave linewrapBursts false
		set_interface_property avalon_dma_control_slave maximumPendingReadTransactions 0
		set_interface_property avalon_dma_control_slave minimumUninterruptedRunLength 1
		set_interface_property avalon_dma_control_slave printableDevice false
		set_interface_property avalon_dma_control_slave readLatency 1
		set_interface_property avalon_dma_control_slave readWaitTime 0
		set_interface_property avalon_dma_control_slave setupTime 0
		set_interface_property avalon_dma_control_slave timingUnits cycles
		set_interface_property avalon_dma_control_slave writeWaitTime 0

		add_interface_port avalon_dma_control_slave slave_address address Input 8
		add_interface_port avalon_dma_control_slave slave_byteenable byteenable Input 4
		add_interface_port avalon_dma_control_slave slave_read read Input 1
		add_interface_port avalon_dma_control_slave slave_write write Input 1
		add_interface_port avalon_dma_control_slave slave_writedata writedata Input 32
		add_interface_port avalon_dma_control_slave slave_readdata readdata Output 32
		
		
		
		# |
		# +-----------------------------------

		# +-----------------------------------
		# | connection point avalon_dma_master
		# | 
		add_interface avalon_dma_master avalon start
		set_interface_property avalon_dma_master associatedClock clk
		set_interface_property avalon_dma_master associatedReset reset
		set_interface_property avalon_dma_master burstOnBurstBoundariesOnly false
		set_interface_property avalon_dma_master doStreamReads false
		set_interface_property avalon_dma_master doStreamWrites false
		set_interface_property avalon_dma_master linewrapBursts false

		add_interface_port avalon_dma_master master_address address Output 32
		add_interface_port avalon_dma_master master_waitrequest waitrequest Input 1
		add_interface_port avalon_dma_master master_write write Output 1
		add_interface_port avalon_dma_master master_writedata writedata Output $mdw
		add_interface_port avalon_dma_master master_byteenable byteenable Output [expr $mdw/8]
		add_interface_port avalon_dma_master master_burstcount burstcount Output 4
		
		
		
		
		# | 
		# +-----------------------------------
	} else {
		# +-----------------------------------
		# | connection point avalon_dma_master
		# | 
		add_interface avalon_dma_master avalon start
		set_interface_property avalon_dma_master associatedClock clk
		set_interface_property avalon_dma_master associatedReset reset
		set_interface_property avalon_dma_master burstOnBurstBoundariesOnly false
		set_interface_property avalon_dma_master doStreamReads false
		set_interface_property avalon_dma_master doStreamWrites false
		set_interface_property avalon_dma_master linewrapBursts false

		add_interface_port avalon_dma_master master_address address Output 32
		add_interface_port avalon_dma_master master_waitrequest waitrequest Input 1
		add_interface_port avalon_dma_master master_read read Output 1
		add_interface_port avalon_dma_master master_readdata readdata Input $mdw
		add_interface_port avalon_dma_master master_readdatavalid readdatavalid Input 1
		add_interface_port avalon_dma_master master_byteenable byteenable Output [expr $mdw/8]
		add_interface_port avalon_dma_master master_burstcount burstcount Output 4
		
		
		
		
		# | 
		# +-----------------------------------

		# +-----------------------------------
		# | connection point avalon_dma_control_slave
		# | 
		add_interface avalon_dma_control_slave avalon end
		set_interface_property avalon_dma_control_slave addressAlignment DYNAMIC
		set_interface_property avalon_dma_control_slave associatedClock clk
		set_interface_property avalon_dma_control_slave associatedReset reset
		set_interface_property avalon_dma_control_slave bridgesToMaster ""
		set_interface_property avalon_dma_control_slave burstOnBurstBoundariesOnly false
		#set_interface_property avalon_dma_control_slave explicitAddressSpan 16
		set_interface_property avalon_dma_control_slave holdTime 0
		set_interface_property avalon_dma_control_slave isBigEndian  false
		set_interface_property avalon_dma_control_slave isFlash false
		set_interface_property avalon_dma_control_slave isMemoryDevice false
		set_interface_property avalon_dma_control_slave isNonVolatileStorage false
		set_interface_property avalon_dma_control_slave linewrapBursts false
		set_interface_property avalon_dma_control_slave maximumPendingReadTransactions 0
		set_interface_property avalon_dma_control_slave minimumUninterruptedRunLength 1
		set_interface_property avalon_dma_control_slave printableDevice false
		set_interface_property avalon_dma_control_slave readLatency 1
		set_interface_property avalon_dma_control_slave readWaitTime 0
		set_interface_property avalon_dma_control_slave setupTime 0
		set_interface_property avalon_dma_control_slave timingUnits cycles
		set_interface_property avalon_dma_control_slave writeWaitTime 0

		add_interface_port avalon_dma_control_slave slave_address address Input 8
		add_interface_port avalon_dma_control_slave slave_byteenable byteenable Input 4
		add_interface_port avalon_dma_control_slave slave_read read Input 1
		add_interface_port avalon_dma_control_slave slave_write write Input 1
		add_interface_port avalon_dma_control_slave slave_writedata writedata Input 32
		add_interface_port avalon_dma_control_slave slave_readdata readdata Output 32
		# |
		# +-----------------------------------

		# +-----------------------------------
		# | connection point avalon_pixel_source
		# | 
		add_interface avalon_pixel_source avalon_streaming start
		set_interface_property avalon_pixel_source associatedClock clk
		set_interface_property avalon_pixel_source associatedReset reset
		set_interface_property avalon_pixel_source dataBitsPerSymbol $bits_per_pixel
		set_interface_property avalon_pixel_source errorDescriptor ""
		set_interface_property avalon_pixel_source maxChannel 0
		set_interface_property avalon_pixel_source readyLatency 0
		set_interface_property avalon_pixel_source symbolsPerBeat $parallelization_ratio

		add_interface_port avalon_pixel_source stream_ready ready Input 1
		add_interface_port avalon_pixel_source stream_data data Output $dw
		add_interface_port avalon_pixel_source stream_startofpacket startofpacket Output 1
		add_interface_port avalon_pixel_source stream_endofpacket endofpacket Output 1
#		add_interface_port avalon_pixel_source stream_empty empty Output 2
		add_interface_port avalon_pixel_source stream_valid valid Output 1
		# | 
		# +-----------------------------------
		
		
	}
}
# | 
# +-----------------------------------

# +-----------------------------------
# | Generation function
# | 
proc generate {} {
	send_message info "Starting Generation of Video DMA Controller"
	
	# get parameter values
	set mode 				[ get_parameter_value "mode" ]
	set num_pixels_in_frame				[ get_parameter_value "num_pixels_in_frame" ]
	set bits_per_pixel			[ get_parameter_value "bits_per_pixel" ]
	set parallelization_ratio		[ get_parameter_value "parallelization_ratio" ]
	set dma_enabled		[ get_parameter_value "dma_enabled" ]
	set use_external_backbuffer		[ get_parameter_value "use_external_backbuffer" ]
	set always_do_buffer_swap		[ get_parameter_value "always_do_buffer_swap" ]
	set swap_symbols_for_ddr_write		[ get_parameter_value "swap_symbols_for_ddr_write" ]
	set watchdog_enabled		[ get_parameter_value "watchdog_enabled" ]
	set watchdog_count		[ get_parameter_value "watchdog_count" ]
	set num_watchdog_bits	 [ get_parameter_value "num_watchdog_bits" ]
	set num_of_dma_locations [expr {$num_pixels_in_frame/$parallelization_ratio}];
	set	override_external_swap_buffers_now         [ get_parameter_value "override_external_swap_buffers_now"         ]
	set override_val_for_external_swap_buffers_now [ get_parameter_value "override_val_for_external_swap_buffers_now" ]
	set address_width [ get_parameter_value "address_width" ]
	
	
	set dw			[ format "DW:%d" [ expr (($bits_per_pixel * $parallelization_ratio) - 1) ] ]
	set ew 		"EW:[expr {[my_clog 2 $parallelization_ratio]-1}]"
	
	set num_pixels_in_frame_p		"NUM_PIXELS_IN_FRAME_DEFAULT:$num_pixels_in_frame"
	set num_of_dma_locations_p	"NUM_OF_DMA_LOCATIONS_DEFAULT:$num_of_dma_locations"

	set mdw "MDW:[expr {[compute_mdw [expr $bits_per_pixel * $parallelization_ratio]] - 1}]"

	set num_watchdog_bits_p "WATCHDOG_COUNT_NUMBITS:$num_watchdog_bits"
	set watchdog_count_p "MAX_WATCHDOG_COUNT:64'd$watchdog_count"

	set bits_per_pixel_p 	[ format "BITS_PER_PIXEL:32'd%d" 	$bits_per_pixel  ]
	set parallelization_ratio_p	[ format "PARALLELIZATION_RATIO:32'd%d" 	$parallelization_ratio]
	set address_width_p 	[ format "LENGTH_ADDRESSWIDTH:32'd%d" 	$address_width  ]

	set dma_enabled_p	"DEFAULT_DMA_ENABLED:1'b0"
	if { $dma_enabled } {
		set dma_enabled_p	"DEFAULT_DMA_ENABLED:1'b1"
	}
	
	
         
	set override_external_swap_buffers_now_p "DEFAULT_OVERRIDE_EXTERNAL_SWAP_BUFFERS_NOW:1'b0";
    if { $override_external_swap_buffers_now } {
	    set override_external_swap_buffers_now_p "DEFAULT_OVERRIDE_EXTERNAL_SWAP_BUFFERS_NOW:1'b1";
	}

    
    set override_val_for_external_swap_buffers_now_p "DEFAULT_AVMM_EXTERNAL_SWAP_BUFFERS_NOW_VAL:1'b0"	
	if { $override_val_for_external_swap_buffers_now  } {
	   set override_val_for_external_swap_buffers_now_p "DEFAULT_AVMM_EXTERNAL_SWAP_BUFFERS_NOW_VAL:1'b1"	
	}
	
	set use_external_backbuffer_p	"DEFAULT_USE_EXTERNAL_BACKBUFFER_ADDRESS:1'b0"
	if { $use_external_backbuffer } {
		set use_external_backbuffer_p	"DEFAULT_USE_EXTERNAL_BACKBUFFER_ADDRESS:1'b1"
	}
	
	set swap_symbols_for_ddr_write_p	"SWAP_SYMBOL_ORDER_TO_FROM_DDR:1'b0"
	if { $swap_symbols_for_ddr_write } {
		set swap_symbols_for_ddr_write_p	"SWAP_SYMBOL_ORDER_TO_FROM_DDR:1'b1"
	}
	
	set always_do_buffer_swap_p	"DEFAULT_ALWAYS_DO_BUFFER_SWAP:1'b0"
	if { $always_do_buffer_swap } {
		set always_do_buffer_swap_p	"DEFAULT_ALWAYS_DO_BUFFER_SWAP:1'b1"
	}
	
	set watchdog_enabled_p	"WATCHDOG_ENABLED:1'b0"
	if { $watchdog_enabled } {
		set watchdog_enabled_p "WATCHDOG_ENABLED:1'b1"
	}
	# set section values
	set use_to_memory "USE_TO_MEMORY:0"
	if { $mode == "From Stream to Memory" } {
		set use_to_memory "USE_TO_MEMORY:1"
	}

	# set arguments
	set params "$dw;$ew;$num_pixels_in_frame_p;$num_of_dma_locations_p;$address_width_p;$mdw;$num_watchdog_bits_p;$watchdog_count_p;$override_external_swap_buffers_now_p;$override_val_for_external_swap_buffers_now_p;$bits_per_pixel_p;$parallelization_ratio_p;$dma_enabled_p;$use_external_backbuffer_p;$always_do_buffer_swap_p;$watchdog_enabled_p;$swap_symbols_for_ddr_write_p"
	set sections "$use_to_memory"

	# get generation settings
#	set dest_language	[ get_generation_property HDL_LANGUAGE ]
	set dest_dir 		[ get_generation_property OUTPUT_DIRECTORY ]
	set dest_name		[ get_generation_property OUTPUT_NAME ]
	
	add_file "$dest_dir$dest_name.v" {SYNTHESIS SIMULATION}
	# add_file "$dest_dir/frame_buffer_video_dma_control_slave.v" SYNTHESIS
	# add_file "$dest_dir/frame_buffer_video_dma_to_memory.v" SYNTHESIS
	# add_file "$dest_dir/frame_buffer_video_dma_to_stream.v" SYNTHESIS

	# Generate HDL
	alt_up_generate "$dest_dir$dest_name.v" "hdl/frame_buffer_avalon_video_dma_controller.v" "frame_buffer_avalon_video_dma_controller" $dest_name $params $sections
	# file copy -force "hdl/frame_buffer_video_dma_control_slave.v" $dest_dir
	# file copy -force "hdl/frame_buffer_video_dma_to_memory.v" $dest_dir
	# file copy -force "hdl/frame_buffer_video_dma_to_stream.v" $dest_dir
}
# | 
# +-----------------------------------

