# TCL File Generated by Component Editor 12.1sp1
# Thu Mar 07 11:35:16 PST 2013
# DO NOT MODIFY


# 
# better_EyeD_controller "better_EyeD_controller" v1.0
# null 2013.03.07.11:35:16
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module better_EyeD_controller
# 
set_module_property NAME better_EyeD_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME better_EyeD_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL better_EyeD_controller
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file better_EyeD_controller.v VERILOG PATH better_EyeD_controller.v

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog TOP_LEVEL better_EyeD_controller
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file better_EyeD_controller.v VERILOG PATH better_EyeD_controller.v


# 
# parameters
# 
add_parameter num_counter_bits NATURAL 12 ""
set_parameter_property num_counter_bits DEFAULT_VALUE 12
set_parameter_property num_counter_bits DISPLAY_NAME num_counter_bits
set_parameter_property num_counter_bits WIDTH ""
set_parameter_property num_counter_bits TYPE NATURAL
set_parameter_property num_counter_bits UNITS None
set_parameter_property num_counter_bits ALLOWED_RANGES 0:2147483647
set_parameter_property num_counter_bits DESCRIPTION ""
set_parameter_property num_counter_bits HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 2
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 read_data readdata Output 32
add_interface_port avalon_slave_0 read_now read Input 1
add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 write_data writedata Input 32
add_interface_port avalon_slave_0 write_now write Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end sample_clk export Input 1
add_interface_port conduit_end Baud_Clk export Input 1
add_interface_port conduit_end measurement_block_count export Output num_counter_bits
add_interface_port conduit_end measurement_block_count_limit export Input num_counter_bits
add_interface_port conduit_end measurement_sample_count export Output num_counter_bits
add_interface_port conduit_end measurement_sample_count_limit export Input num_counter_bits
add_interface_port conduit_end clear_counters export Output 1
add_interface_port conduit_end enable export Output 1
add_interface_port conduit_end all_samples_measured export Output 1
add_interface_port conduit_end acquisition_fifo_write_enable export Output 1
add_interface_port conduit_end measuring_a_block_now export Output 1
add_interface_port conduit_end dummy_reset export Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink BusCLK clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock ""
set_interface_property reset_sink synchronousEdges NONE
set_interface_property reset_sink ENABLED true

add_interface_port reset_sink reset reset Input 1

