# TCL File Generated by Component Editor 14.1
# Sat Apr 25 12:11:21 CDT 2015
# DO NOT MODIFY


# 
# aligner_tbstub "aligner_tbstub" v1.0
#  2015.04.25.12:11:21
# 
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.1


# 
# module aligner_tbstub
# 
set_module_property DESCRIPTION ""
set_module_property NAME aligner_tbstub
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME aligner_tbstub
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL aligner_tbstub
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file aligner_tbstub.sv SYSTEM_VERILOG PATH ../LVDS/aligner_tbstub.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL aligner_tbstub
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file aligner_tbstub.sv SYSTEM_VERILOG PATH ../LVDS/aligner_tbstub.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL aligner_tbstub
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file aligner_tbstub.sv SYSTEM_VERILOG PATH ../LVDS/aligner_tbstub.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point aligner1_ctrl
# 
add_interface aligner1_ctrl conduit end
set_interface_property aligner1_ctrl associatedClock ""
set_interface_property aligner1_ctrl associatedReset ""
set_interface_property aligner1_ctrl ENABLED true
set_interface_property aligner1_ctrl EXPORT_OF ""
set_interface_property aligner1_ctrl PORT_NAME_MAP ""
set_interface_property aligner1_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property aligner1_ctrl SVD_ADDRESS_GROUP ""

add_interface_port aligner1_ctrl aligner1_shift aligner_shift Output 1
add_interface_port aligner1_ctrl aligner1_oos aligner_oos Input 1
add_interface_port aligner1_ctrl aligner1_ena aligner_ena Output 1


# 
# connection point aligner2_ctrl
# 
add_interface aligner2_ctrl conduit end
set_interface_property aligner2_ctrl associatedClock ""
set_interface_property aligner2_ctrl associatedReset ""
set_interface_property aligner2_ctrl ENABLED true
set_interface_property aligner2_ctrl EXPORT_OF ""
set_interface_property aligner2_ctrl PORT_NAME_MAP ""
set_interface_property aligner2_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property aligner2_ctrl SVD_ADDRESS_GROUP ""

add_interface_port aligner2_ctrl aligner2_ena aligner_ena Output 1
add_interface_port aligner2_ctrl aligner2_shift aligner_shift Output 1
add_interface_port aligner2_ctrl aligner2_oos aligner_oos Input 1

