# TCL File Generated by Component Editor 10.0sp1
# Wed Mar 21 17:28:02 PDT 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | dual_port_memory_controller_avalon_mm "dual_port_memory_controller_avalon_mm" v2.0
# | Yair Linn 2012.03.21.17:28:02
# | Controller for dual port memory (without the memory itself)
# | 
# | /usr/export/home/kurnool/nobackup/svn_tests/reissue_for_dac_mux/ifast_sas3_for_rel25_checkin3/fpgas/ifast_base_w_enet/rtl/iFAST/iFAST_RTL_Library/dual_port_memory_controller_avalon_mm.v
# | 
# |    ./dual_port_memory_controller_avalon_mm.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module dual_port_memory_controller_avalon_mm
# | 
set_module_property DESCRIPTION "Controller for dual port memory (without the memory itself)"
set_module_property NAME dual_port_memory_controller_avalon_mm
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property GROUP "Memories and Memory Controllers"
set_module_property AUTHOR "Yair Linn"
set_module_property DISPLAY_NAME dual_port_memory_controller_avalon_mm
set_module_property TOP_LEVEL_HDL_FILE dual_port_memory_controller_avalon_mm.v
set_module_property TOP_LEVEL_HDL_MODULE dual_port_memory_controller_avalon_mm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file dual_port_memory_controller_avalon_mm.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter num_addr_bits INTEGER 12
set_parameter_property num_addr_bits DEFAULT_VALUE 12
set_parameter_property num_addr_bits DISPLAY_NAME num_addr_bits
set_parameter_property num_addr_bits TYPE INTEGER
set_parameter_property num_addr_bits UNITS None
set_parameter_property num_addr_bits ALLOWED_RANGES -2147483648:2147483647
set_parameter_property num_addr_bits AFFECTS_GENERATION false
set_parameter_property num_addr_bits HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 associatedClock clock_reset
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 1
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 5
set_interface_property avalon_slave_0 readWaitTime 5
set_interface_property avalon_slave_0 setupTime 1
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 address address Input num_addr_bits
add_interface_port avalon_slave_0 read_data readdata Output 32
add_interface_port avalon_slave_0 write_data writedata Input 32
add_interface_port avalon_slave_0 read_now read Input 1
add_interface_port avalon_slave_0 write_now write Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end addr_to_dp_ram export Output num_addr_bits
add_interface_port conduit_end data_from_dp_ram export Input 32
add_interface_port conduit_end data_to_dp_ram export Output 32
add_interface_port conduit_end clk_to_dp_ram export Output 1
add_interface_port conduit_end write_en export Output 1
add_interface_port conduit_end read_en export Output 1
# | 
# +-----------------------------------
